### ISSUE TITLE
Erro Cap. 12.6

### ISSUE THREAD

**Issue by Dhenner** [flaviohenriquealmeida/mean-livro-codigo#10]
Finalizando o cap. 12 me deparo com este erro do travis-ci, não sei o motivo dele conseguir clonar meu repositorio no guithub.

https://github.com/Dhenner/contatooh

Using worker: worker-linux-12-2.bb.travis-ci.org:travis-linux-5

travis_fold:start:system_info
[0K[33;1mBuild system information[0m
Build language: node_js
[34m[1mBuild image provisioning date and time[0m
Fri Dec 26 15:36:46 UTC 2014
[34m[1mlsb_release -a[0m
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04 LTS
Release:	12.04
Codename:	precise
[34m[1mCookbooks Version[0m
984d1aa https://github.com/travis-ci/travis-cookbooks/tree/984d1aa
[34m[1mGCC version[0m
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[34m[1mLLVM version[0m
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
[34m[1mPre-installed Ruby versions[0m
ruby-1.9.3-p551
[34m[1mPre-installed Node.js versions[0m
v0.10
v0.10.18
v0.10.33
v0.10.35
v0.11.14
v0.6.21
v0.8.27
[34m[1mPre-installed Go versions[0m
go1.4
[34m[1mRedis version[0m
redis-server 2.8.18
[34m[1mriak version[0m
1.4.12
[34m[1mMongoDB version[0m
MongoDB 2.4.12
[34m[1mCouchDB version[0m
couchdb 1.6.1
[34m[1mNeo4j version[0m
1.9.4
[34m[1mCassandra version[0m
2.0.9
[34m[1mRabbitMQ Version[0m
3.4.2
[34m[1mElasticSearch version[0m
1.4.0
[34m[1mInstalled Sphinx versions[0m
2.0.10
2.1.9
2.2.4
[34m[1mDefault Sphinx version[0m
2.1.9
[34m[1mInstalled Firefox version[0m
firefox 31.0esr
[34m[1mPhantomJS version[0m
1.9.8
[34m[1mant -version[0m
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
[34m[1mmvn -version[0m
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T20:58:10+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_72, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-042stab090.5", arch: "amd64", family: "unix"
travis_fold:end:system_info
[0K
travis_fold:start:git.checkout
[0Ktravis_time:start:1b3ac698
[0K$ git clone --depth=50 --branch=master git://github.com/Dhenner/contatooh.git Dhenner/contatooh
Cloning into 'Dhenner/contatooh'...
remote: Counting objects: 61, done.[K
remote: Compressing objects:   1% (1/59)   [K
remote: Compressing objects:   3% (2/59)   [K
remote: Compressing objects:   5% (3/59)   [K
remote: Compressing objects:   6% (4/59)   [K
remote: Compressing objects:   8% (5/59)   [K
remote: Compressing objects:  10% (6/59)   [K
remote: Compressing objects:  11% (7/59)   [K
remote: Compressing objects:  13% (8/59)   [K
remote: Compressing objects:  15% (9/59)   [K
remote: Compressing objects:  16% (10/59)   [K
remote: Compressing objects:  18% (11/59)   [K
remote: Compressing objects:  20% (12/59)   [K
remote: Compressing objects:  22% (13/59)   [K
remote: Compressing objects:  23% (14/59)   [K
remote: Compressing objects:  25% (15/59)   [K
remote: Compressing objects:  27% (16/59)   [K
remote: Compressing objects:  28% (17/59)   [K
remote: Compressing objects:  30% (18/59)   [K
remote: Compressing objects:  32% (19/59)   [K
remote: Compressing objects:  33% (20/59)   [K
remote: Compressing objects:  35% (21/59)   [K
remote: Compressing objects:  37% (22/59)   [K
remote: Compressing objects:  38% (23/59)   [K
remote: Compressing objects:  40% (24/59)   [K
remote: Compressing objects:  42% (25/59)   [K
remote: Compressing objects:  44% (26/59)   [K
remote: Compressing objects:  45% (27/59)   [K
remote: Compressing objects:  47% (28/59)   [K
remote: Compressing objects:  49% (29/59)   [K
remote: Compressing objects:  50% (30/59)   [K
remote: Compressing objects:  52% (31/59)   [K
remote: Compressing objects:  54% (32/59)   [K
remote: Compressing objects:  55% (33/59)   [K
remote: Compressing objects:  57% (34/59)   [K
remote: Compressing objects:  59% (35/59)   [K
remote: Compressing objects:  61% (36/59)   [K
remote: Compressing objects:  62% (37/59)   [K
remote: Compressing objects:  64% (38/59)   [K
remote: Compressing objects:  66% (39/59)   [K
remote: Compressing objects:  67% (40/59)   [K
remote: Compressing objects:  69% (41/59)   [K
remote: Compressing objects:  71% (42/59)   [K
remote: Compressing objects:  72% (43/59)   [K
remote: Compressing objects:  74% (44/59)   [K
remote: Compressing objects:  76% (45/59)   [K
remote: Compressing objects:  77% (46/59)   [K
remote: Compressing objects:  79% (47/59)   [K
remote: Compressing objects:  81% (48/59)   [K
remote: Compressing objects:  83% (49/59)   [K
remote: Compressing objects:  84% (50/59)   [K
remote: Compressing objects:  86% (51/59)   [K
remote: Compressing objects:  88% (52/59)   [K
remote: Compressing objects:  89% (53/59)   [K
remote: Compressing objects:  91% (54/59)   [K
remote: Compressing objects:  93% (55/59)   [K
remote: Compressing objects:  94% (56/59)   [K
remote: Compressing objects:  96% (57/59)   [K
remote: Compressing objects:  98% (58/59)   [K
remote: Compressing objects: 100% (59/59)   [K
remote: Compressing objects: 100% (59/59), done.[K
Receiving objects:   1% (1/61)   
Receiving objects:   3% (2/61)   
Receiving objects:   4% (3/61)   
Receiving objects:   6% (4/61)   
Receiving objects:   8% (5/61)   
Receiving objects:   9% (6/61)   
Receiving objects:  11% (7/61)   
Receiving objects:  13% (8/61)   
Receiving objects:  14% (9/61)   
Receiving objects:  16% (10/61)   
Receiving objects:  18% (11/61)   
Receiving objects:  19% (12/61)   
Receiving objects:  21% (13/61)   
Receiving objects:  22% (14/61)   
Receiving objects:  24% (15/61)   
Receiving objects:  26% (16/61)   
Receiving objects:  27% (17/61)   
Receiving objects:  29% (18/61)   
Receiving objects:  31% (19/61)   
Receiving objects:  32% (20/61)   
Receiving objects:  34% (21/61)   
Receiving objects:  36% (22/61)   
Receiving objects:  37% (23/61)   
Receiving objects:  39% (24/61)   
Receiving objects:  40% (25/61)   
Receiving objects:  42% (26/61)   
Receiving objects:  44% (27/61)   
Receiving objects:  45% (28/61)   
Receiving objects:  47% (29/61)   
Receiving objects:  49% (30/61)   
Receiving objects:  50% (31/61)   
Receiving objects:  52% (32/61)   
Receiving objects:  54% (33/61)   
Receiving objects:  55% (34/61)   
Receiving objects:  57% (35/61)   
Receiving objects:  59% (36/61)   
Receiving objects:  60% (37/61)   
Receiving objects:  62% (38/61)   
Receiving objects:  63% (39/61)   
Receiving objects:  65% (40/61)   
Receiving objects:  67% (41/61)   
remote: Total 61 (delta 1), reused 61 (delta 1)[K
Receiving objects:  68% (42/61)   
Receiving objects:  70% (43/61)   
Receiving objects:  72% (44/61)   
Receiving objects:  73% (45/61)   
Receiving objects:  75% (46/61)   
Receiving objects:  77% (47/61)   
Receiving objects:  78% (48/61)   
Receiving objects:  80% (49/61)   
Receiving objects:  81% (50/61)   
Receiving objects:  83% (51/61)   
Receiving objects:  85% (52/61)   
Receiving objects:  86% (53/61)   
Receiving objects:  88% (54/61)   
Receiving objects:  90% (55/61)   
Receiving objects:  91% (56/61)   
Receiving objects:  93% (57/61)   
Receiving objects:  95% (58/61)   
Receiving objects:  96% (59/61)   
Receiving objects:  98% (60/61)   
Receiving objects: 100% (61/61)   
Receiving objects: 100% (61/61), 14.71 KiB | 0 bytes/s, done.
Resolving deltas:   0% (0/1)   
Resolving deltas: 100% (1/1)   
Resolving deltas: 100% (1/1), done.
Checking connectivity... done.
travis_time:end:1b3ac698:start=1422324834412410212,finish=1422324834476636321,duration=64226109
[0K$ cd Dhenner/contatooh
$ git checkout -qf 8158fc59aa347c2dd8d39345d0e748ca9da2b815
fatal: reference is not a tree: 8158fc59aa347c2dd8d39345d0e748ca9da2b815

[31;1mThe command "git checkout -qf 8158fc59aa347c2dd8d39345d0e748ca9da2b815" failed and exited with 128 during .[0m

Your build has been stopped.

**Comment by flaviohenriquealmeida** [comment]
Parece  uma inconsistência no seu repo. Ou vc pesquisa e vê como resolver (
link abaixo) ou vc, para não perder tempo remove esse repo do travis
primeiro, deleta o repo e cria um novo a partir do seu projeto. Se vc está
em deploy, apaga e cria a app novamente.

https://groups.google.com/forum/m/#!topic/travis-ci/wDNpBGosAGo
Em 27/01/2015 00:37, "Dhenner" <notifications@github.com> escreveu:

**Comment by flaviohenriquealmeida** [comment]
Como você resolveu Dhemer?

**Comment by Dhenner** [comment]
Ainda não tive tempo para descobrir a falha, quando verificar te retorno.

2015-02-10 16:11 GMT-02:00 Flavio Henrique de Souza Almeida <
notifications@github.com>:

> Como você resolveu Dhemer?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/10#issuecomment-73751223>
> .
>



-- 
Att
Dhenner Santos Peres
