### ISSUE TITLE
Autenticação e Autorização

### ISSUE THREAD

**Issue by RicardoOliveiraFilho** [flaviohenriquealmeida/mean-livro-codigo#11]
Opa Flávio, boa noite!!!!

Cara, você por acaso teria alguma fonte que me pudesse ajudar a respeito da implementação de um Custom Login???????
Confesso que fiquei meio surpreso quando constatei que o Capítulo 8 não abordou algo do gênero...
^_^'

Desde já, grato!!!!

**Comment by flaviohenriquealmeida** [comment]
Olá RicardoOliveiraFilho, vamos lá!

Primeiro, quero combinar de usarmos este canal apenas para postar issues do livro. Por quê? Cada issue que pinta aqui eu sou notificado no meu celular e venho correndo ver se é algum problema no livro. Porém, eu entendo que a ausência desse "custom login" não deixe de ser uma issue para você certo?

Bom, já que postou aqui, vamos lá. Você ficou surpreso, porque espera outra forma de autenticação, mas eu não ficaria tão surpreso assim. Qual o motivo? Se você quer um custom login, terá que cuidar deste banco, ou seja, você terá que se preocupar com toda infra e questões de segurança que envolvem o armazenamento de credenciais. Lembra o caso da PSN que foi invadida e roubaram os dados de zilhões de usuários?

A ideia do projeto do livro é delegarmos sempre que possível a parte da infra da aplicação para serviços, inclusive fizemos não apenas com autenticação, mas integração contínua e testes. Tudo bem?

Agora vamos à sua pergunta. O que você está querendo no mundo do Passport.js não é um custom login, mas uma local strategy. Este é o termo dado pelo framework quando queremos nos basear no login e senha do usuário para nos autenticarmos. No livro, usamos a estratégia de autenticação do Github, mas existe a passport-local, que é justamente o que você quer: capturar o login e senha do usuário e verificar se ele existe no meu banco. Segue alguns links que podem ajudá-lo:


https://github.com/jaredhanson/passport-local

http://danialk.github.io/blog/2013/02/23/authentication-using-passportjs/  (veja a parte de local-strategy)

http://passportjs.org/guide/configure/


Se você compreendeu a API do passport, alterar o projeto será complicado. Só fique atento que se você alterar o projeto do livro com estratégia local, há outros capítulos que não serão mais aplicados, porque considera OAuth 2.0. Espero ter ajudado.

**Comment by RicardoOliveiraFilho** [comment]
Ajudará sim!!!! Brigadão!!!!
Desculpe o fato de ter criado a Issue! Mas não sabia outra forma de lhe contactar... ^_^'

Eu tinha respondido a respeito do repositório!!!! Acontece que não consegui subir ele... No meu gitHub fica sendo exibida uma mensagem que ele não trata o protocolo https!!!

E na verdade, depois eu descobri que não se tratava de uma falha no filter!!! Acontece que quando eu colocava o filtro ele considerava também o contato presente na Emergência.

Novamente, vá desculpando qualquer coisa e insisto em frisar que o Livro é ótimo!!! Aprendi muito com ele. Com esta sua dica de segurança vou buscar aprender as outras autenticações!!!

Muito obrigado!!!

**Comment by flaviohenriquealmeida** [comment]
Relaxe, tente o lance do local strategy. Para ficar melhor ainda, tente resolver o lance do seu git que assim eu posso te ajudar melhor. Abraço.
