### ISSUE TITLE
Problema com as rotas e metódo delete

### ISSUE THREAD

**Issue by bergandrade** [flaviohenriquealmeida/mean-livro-codigo#12]
Olá Flávio, primeiramente eu gostaria de parabenizá-lo pelo ótimo livro, uma didática incrível!

Então, eu consegui chegar ao capítulo 5 de boa, mas quando chego nesta parte: 
```
app.route('/contatos/:id')
   .get(controller.obtemContato)
   .delete(controller.removeContato);
```

A aplicação simplesmente para por conta do `.delete()`.

Ele indica este erro: `Error: Route.delete() requires callback functions but got a [object Undefined]`

Já comparei com o seu código e está idêntico, só se eu tiver muito desligado e tiver passado despercebido.

O conteúdo está aqui http://github.com/bergandrade/contatooh caso queira dar uma olhada.

**Comment by flaviohenriquealmeida** [comment]
Vou olhar seu código do github. Pode deixar que a gente descobre.
Em 20/02/2015 23:46, "Altemberg Andrade" <notifications@github.com>
escreveu:

**Comment by flaviohenriquealmeida** [comment]
Opa, se código está diferente do que está no meu repo. Em
contatooh/app/controllers/contato.js  você está retornando o controller
antes da definição do de removeContato, por isso ele não está presente no
controller. :) Faça a alteração e me dê um feedback. Outra coisa, como vc
está usando o expresload, não precisa mais dos requires que foram feitos no
cap 2.

Abraço

Em 21 de fevereiro de 2015 16:09, Flávio Henrique Almeida <
flaviohenriquealmeida@gmail.com> escreveu:

> Vou olhar seu código do github. Pode deixar que a gente descobre.
> Em 20/02/2015 23:46, "Altemberg Andrade" <notifications@github.com>
> escreveu:
>
> Olá Flávio, primeiramente eu gostaria de parabenizá-lo pelo ótimo livro,
>> uma didática incrível!
>>
>> Então, eu consegui chegar ao capítulo 5 de boa, mas quando chego nesta
>> parte:
>>
>> app.route('/contatos/:id')
>>    .get(controller.obtemContato)
>>    .delete(controller.removeContato);
>>
>> A aplicação simplesmente para por conta do .delete().
>>
>> Ele indica este erro: Error: Route.delete() requires callback functions
>> but got a [object Undefined]
>>
>> Já comparei com o seu código e está idêntico, só se eu tiver muito
>> desligado e tiver passado despercebido.
>>
>> O conteúdo está aqui http://github.com/bergandrade/contatooh
>> <https://github.com/bergandrade/contatooh> caso queira dar uma olhada.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/12>.
>>
>


-- 
"o único homem educado é o homem que aprendeu a aprender" - Carl R. Rogers

www.caelum.com.br

**Comment by bergandrade** [comment]
Opa, rapaz o problema era esse mesmo. Eu tava analisando tanto e não me toquei que estava retornando o controller antes do removeContato.

Muito obrigado pela ajuda, vou tentar prestar mais atenção agora rsrs.

Abraço.

**Comment by flaviohenriquealmeida** [comment]
Relaxa, bom estudo!
Em 21/02/2015 16:45, "Altemberg Andrade" <notifications@github.com>
escreveu:
