### ISSUE TITLE
Erro ao se autenticar no github: Unknown authentication strategy "github"

### ISSUE THREAD

**Issue by clovisdasilvaneto** [flaviohenriquealmeida/mean-livro-codigo#13]
Olá flávio, primeiramente, gostaria de parabenizá-lo pelo livro MEAN.

Seguinte, estou com um erro ao clicar no botao de entrar pelo github: 

Error: Unknown authentication strategy "github"
   at attempt (C:\xampp\htdocs\MEAN_teste\node_modules\passport\lib\middleware\authenticate.js:166:37)
   at authenticate (C:\xampp\htdocs\MEAN_teste\node_modules\passport\lib\middleware\authenticate.js:342:7)
   at Layer.handle [as handle_request] (C:\xampp\htdocs\MEAN_teste\node_modules\express\lib\router\layer.js:76:5)
   at next (C:\xampp\htdocs\MEAN_teste\node_modules\express\lib\router\route.js:100:13)
   at Route.dispatch (C:\xampp\htdocs\MEAN_teste\node_modules\express\lib\router\route.js:81:3)
   at Layer.handle [as handle_request] (C:\xampp\htdocs\MEAN_teste\node_modules\express\lib\router\layer.js:76:5)
   at C:\xampp\htdocs\MEAN_teste\node_modules\express\lib\router\index.js:227:24
   at Function.proto.process_params (C:\xampp\htdocs\MEAN_teste\node_modules\express\lib\router\index.js:305:12)
   at C:\xampp\htdocs\MEAN_teste\node_modules\express\lib\router\index.js:221:12
   at Function.match_layer (C:\xampp\htdocs\MEAN_teste\node_modules\express\lib\router\index.js:288:3)

Já li e ré-li no pdf e ta tudo iguasinho :(

**Comment by flaviohenriquealmeida** [comment]
Vou dar uma olhada. Eu testei o código do meu repo no windows e funciona.
Fiquei curioso para descobrir seu problema
Em 26/02/2015 06:11, "Clóvis Neto" <notifications@github.com> escreveu:

**Comment by clovisdasilvaneto** [comment]
O link do meu repositório é este: https://github.com/clovisdasilvaneto/projeto-mean

**Comment by flaviohenriquealmeida** [comment]
Só devo ver amanhã, estou enrolado.  Enquanto isso reinstala o github
estrategy pelo npm verificando se houve alguma msg de erro. Use a versão
que o livro solicita.
Em 26/02/2015 10:56, "Flávio Henrique Almeida" <
flaviohenriquealmeida@gmail.com> escreveu:

**Comment by flaviohenriquealmeida** [comment]
Outra coisa: vai no meu repo e roda o projeto do cap no seu Windows. Siga
as instruções do readme.
Em 26/02/2015 11:02, escreveu:

**Comment by clovisdasilvaneto** [comment]
Beleza, quanto ao re-instalar o estrategy, já fiz mas nada aconteceu :/

**Comment by flaviohenriquealmeida** [comment]
Só um detalhe. Vc está com uma versão desatualizada do livro. Baixe a nova
versão da casa do codigo. Tudo bem?
Em 26/02/2015 11:08, "Clóvis Neto" <notifications@github.com> escreveu:

**Comment by clovisdasilvaneto** [comment]
putz, deve ser por isso ¬¬' beleza

**Comment by flaviohenriquealmeida** [comment]
Talvez não, porque até essa parte, mesmo o livro versão 1.0 já funcionava.
Mas dá uma olhada. Na primeira errata do livro, auth.ejs virou auth.html e
para controlar o acesso no client é usado interceptadores do Angular. Fica
tranquilo que a gente descobre o problema, eu só estou é meio enrolado hoje
e um pouco amanhã!

2015-02-26 11:58 GMT-03:00 Clóvis Neto <notifications@github.com>:

> putz, deve ser por isso ¬¬' beleza
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/13#issuecomment-76191909>
> .
>



-- 
"o único homem educado é o homem que aprendeu a aprender" - Carl R. Rogers

www.caelum.com.br

**Comment by flaviohenriquealmeida** [comment]
Descobri o problema no seu código. O arquivo express.js não está
configurado como o livro pede no seguinte sentido: você ativou o middleware
express.static depois do carregamento de rotas com o express-load. O
ativamente do middleware deve ser após a configuração do view engine:

  app.set('view engine', 'ejs');
  app.set('views','./app/views');
  app.use(express.static('./public'));

Você foi vítima do middleware hell, isto é, a ordem de carregamento do
middleware influencia o resultado final.

Clóvis, mesmo que você faça a alteração, sugiro que baixe a versão mais
atual do livro. Ela utiliza interceptadores do angularjs para resolver o
problema do redirecionamento da suas parciais quando o usuário não tem
autorização.

Espero ter ajudado. Abraço!

Em 26 de fevereiro de 2015 13:14, Flávio Henrique Almeida <
flaviohenriquealmeida@gmail.com> escreveu:

> Talvez não, porque até essa parte, mesmo o livro versão 1.0 já funcionava.
> Mas dá uma olhada. Na primeira errata do livro, auth.ejs virou auth.html e
> para controlar o acesso no client é usado interceptadores do Angular. Fica
> tranquilo que a gente descobre o problema, eu só estou é meio enrolado hoje
> e um pouco amanhã!
>
> 2015-02-26 11:58 GMT-03:00 Clóvis Neto <notifications@github.com>:
>
>> putz, deve ser por isso ¬¬' beleza
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/13#issuecomment-76191909>
>> .
>>
>
>
>
> --
> "o único homem educado é o homem que aprendeu a aprender" - Carl R. Rogers
>
> www.caelum.com.br
>



-- 
"o único homem educado é o homem que aprendeu a aprender" - Carl R. Rogers

www.caelum.com.br

**Comment by clovisdasilvaneto** [comment]
putz, é verdade, vou dar uma ajeitada aqui e dou um retorno

**Comment by clovisdasilvaneto** [comment]
Flávio, como posso obter novamente a versão atualizada do livro? pois a que eu comprei ta desatualizada como você falou

**Comment by flaviohenriquealmeida** [comment]
Sua versão é PDF? Se for, basta acessar sua conta no casa do código e
baixar pelo painel o livro novamente.

Em 2 de março de 2015 12:59, Clóvis Neto <notifications@github.com>
escreveu:

> Flávio, como posso obter novamente a versão atualizada do livro? pois a
> que eu comprei ta desatualizada como você falou
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/13#issuecomment-76738047>
> .
>



-- 
"o único homem educado é o homem que aprendeu a aprender" - Carl R. Rogers

www.caelum.com.br

**Comment by clovisdasilvaneto** [comment]
É o ebook digital e o livro :) 
Corrigi a ordem do middleware antes da ordem mas o erro ainda persiste :'( Irei atualizar a versão do meu livro para ver se o danado desse erro some da minha vida

**Comment by flaviohenriquealmeida** [comment]
Tranquilo, quando baixar a nova versão, segue o cap de autenticação
novamente. Mesmo a versão antiga, não era para você receber uma mensagem
erro. Eu alterei seu projeto aqui mudando a ordem do middleware e a
mensagem de erro sumiu.

Em 2 de março de 2015 13:42, Clóvis Neto <notifications@github.com>
escreveu:

> É o ebook digital e o livro :)
> Corrigi a ordem do middleware antes da ordem mas o erro ainda persiste :'(
> Irei atualizar a versão do meu livro para ver se o danado desse erro some
> da minha vida
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/13#issuecomment-76747460>
> .
>



-- 
"o único homem educado é o homem que aprendeu a aprender" - Carl R. Rogers

www.caelum.com.br

**Comment by flaviohenriquealmeida** [comment]
E aí Clovis, tá tudo certo? Conseguiu baixar o atualizado?

**Comment by clovisdasilvaneto** [comment]
fiz hoje, iria comentar pela noite :D ! Tudo certinho maaan :D valeeeu!

**Comment by pedro-hos** [comment]
@flaviohenriquealmeida boa tarde! Estou com o mesmo problema. Meu código está em https://github.com/pedro-hos/mean-workspace/tree/master/livro_mean/contatooh

Refiz o capítulo procurando alguma bobeira minha, mas não encontrei. Poderia me ajudar?

Obrigado

**Comment by pedro-hos** [comment]
Achei o erro. Tinha esquecido de declarar no server.js o passport. Valeu
