### ISSUE TITLE
[OFF] Futuras aplicações

### ISSUE THREAD

**Issue by bergandrade** [flaviohenriquealmeida/mean-livro-codigo#14]
Flávio, minha dúvida agora não é muito em relação ao livro e sim em minhas futuras aplicações utilizando MEAN.

Para todas próximas aplicações que eu for desenvolver utilizando MEAN, eu devo seguir exatamente a mesma estrutura que vc aborda no livro?

Porque uma coisa que me deixou meio confuso foi o fato de que em views só existe um arquivo index.ejs e as outras estão em public/partials e como .html e também alguns controllers.

Os controllers devem ficar sempre separados assim? E caso eu utilize outro template engine, como Jade por exemplo, eu teria que criar apenas um index.jade dentro de views e todas as outras páginas teriam que ser feitas com .html dentro de alguma pasta dentro de public?

Porque estou querendo desenvolver uma outra aplicação com MEAN e me bateu todas essas dúvidas.

**Comment by flaviohenriquealmeida** [comment]
Vou te pedir para postar essa dúvida lá no grupo do facebook. Vamos
combinar e deixar isso aqui apenas para issues do livro, tudo bem?

Assim que postar lá, eu tento responder o mais rápido possível dentro das
minhas limitações de tempo.


Abraço!




Em 9 de março de 2015 14:39, Altemberg Andrade <notifications@github.com>
escreveu:

> Flávio, minha dúvida agora não é muito em relação ao livro e sim em minhas
> futuras aplicações utilizando MEAN.
>
> Para todas próximas aplicações que eu for desenvolver utilizando MEAN, eu
> devo seguir exatamente a mesma estrutura que vc aborda no livro?
>
> Porque uma coisa que me deixou meio confuso foi o fato de que em views só
> existe um arquivo index.ejs e as outras estão em public/partials e como
> .html e também alguns controllers.
>
> Os controllers devem ficar sempre separados assim? E caso eu utilize outro
> template engine, como Jade por exemplo, eu teria que criar apenas um
> index.jade dentro de views e todas as outras páginas teriam que ser feitas
> com .html dentro de alguma pasta dentro de public?
>
> Porque estou querendo desenvolver uma outra aplicação com MEAN e me bateu
> todas essas dúvidas.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/14>.
>



-- 
Flávio Almeida
--------------------------------------------------
Caelum | Ensino e Inovação
http://www.caelum.com.br
(21) 2220-4156

Alura
www.alura.com.br

**Comment by flaviohenriquealmeida** [comment]
Bom, só para acelerar, vou responder por aqui mesmo. Depois entra no grupo, tá?

# Sobre a estrutura do projeto:

	Há diferentes maneiras de organizarmos um projeto MEAN. Por exemplo, o http://mean.io é um gerador de projeto MEAN (MEAN scaffold) que utiliza uma estrutura diferente de http://meanjs.org, 
	outro scaffold de MEAN.

	No livro, a estrutura lembra muito a do mean.io, porém tem algo do meajs.org. Conclusão: a estrutura do projeto tem que ajudar na manutenção e legibilidade do seu projeto, seja qual for. Se você ficou à vontade com a estrutura apresentada no livro, pode segui-la sem problemas.

# index.ejs

	No projeto, index.ejs é a única view processada no lado do servidor para exibir o usuário logado no sistema. A ideia foi mostrar que podemos usar view no client-side com view no server-side sem problemas. O restante continuou na pasta public. Se você não quiser usar view engine no lado do servidor no seu próximo projeto, basta criar o seu index.htnl em public. 

# jade
	Se você quiser usar Jade, pode adotar a mesma estrutura, apenas renomeando arquivos e ativando o template engine em express.js. 

Espero ter ajudado.

**Comment by bergandrade** [comment]
Ah, entendi.

Ajudou sim e muito, Flávio!

Já entrei no grupo lá, dúvidas assim agora posto por lá, desculpa aí e valeu pela ajuda de novo ^^

**Comment by flaviohenriquealmeida** [comment]
Tranquilo, dúvida do projeto, código pode postar aqui ou lá, melhor aqui.
Offtopic pode postar o que quiser lá que eu tento responder :)

Abraço e sucesso!

2015-03-09 15:22 GMT-03:00 Altemberg Andrade <notifications@github.com>:

> Closed #14
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/14>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/14#event-248749685>
> .
>



-- 
Flávio Almeida
--------------------------------------------------
Caelum | Ensino e Inovação
http://www.caelum.com.br
(21) 2220-4156

Alura
www.alura.com.br
