### ISSUE TITLE
Problema Update pág. 181

### ISSUE THREAD

**Issue by adamsalves** [flaviohenriquealmeida/mean-livro-codigo#15]
Olá Flávio, boa noite!
Estou com problemas na hora de atualizar o contato. 
Recebo o seguinte erro: 

{ [MongoError: exception: Mod on _id not allowed]
  name: 'MongoError',
  errmsg: 'exception: Mod on _id not allowed',
  code: 10148,
  ok: 0 }

e a promise da function $scope.salva cai no catch status 500.

o mongoose me retorna isso, mas não salva no banco:

Mongoose: contatos.findAndModify({ _id: ObjectId("551c9d95e141c27c21e73e20") }) [] { '$set': { __v: 0, _id: ObjectId("551c9d95e141c27c21e73e20"), email: 'teste@teste.com', nome: 'Teste' } } { new: true, upsert: false, remove: false }

Você pode dar uma luz!

Obrigado

**Comment by flaviohenriquealmeida** [comment]
Opa! Eu estou sem o note onde estou. Tem como postar no fórum do Facebook?
Tem como compartilhar seu repo do git? Assim que chegar no meu micro eu
vejo para você.

Olá Flávio, boa noite!
Estou com problemas na hora de atualizar o contato.
Recebo o seguinte erro:

{ [MongoError: exception: Mod on _id not allowed]
name: 'MongoError',
errmsg: 'exception: Mod on _id not allowed',
code: 10148,
ok: 0 }

e a promise da function $scope.salva cai no catch status 500.

o mongoose me retorna isso, mas não salva no banco:

Mongoose: contatos.findAndModify({ _id:
ObjectId("551c9d95e141c27c21e73e20") }) [] { '$set': { __v: 0, _id:
ObjectId("551c9d95e141c27c21e73e20"), email: 'teste@teste.com', nome:
'Teste' } } { new: true, upsert: false, remove: false }

Você pode dar uma luz!

Obrigado

—
Reply to this email directly or view it on GitHub
<https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/15>.

**Comment by adamsalves** [comment]
Ola Flavio,
 
Fiz umas pesquisas e consegui uma solução, porem não sei se é o melhor a se fazer!

No arquivo app/controllers/contato.js  adicionei "delete req.body._id;" no salvaContato e consegui fazer o update. Está ok agora. Devo ter deixado algo de lado, já que no seu código isso não é necessário.

Aqui está o repo: https://github.com/adamsalves/contatooh

**Comment by flaviohenriquealmeida** [comment]
Baixei seu projeto e vi que você está usando uma versão não instável do
Mongoose. Estranho, rodei novamente
npm install mongoose@3.8 --save

E agora passou a mensagem de warning. O estranho é que no seu package.json
está lá a versão 3.8 e não a 3.9 que ele baixo. Pode confirmar se você
recebe esta mensagem:

##############################################################

#

#   !!! MONGOOSE WARNING !!!

#

#   This is an UNSTABLE release of Mongoose.

#   Unstable releases are available for preview/testing only.

#   DO NOT run this in production.

#

##############################################################


Outra coisa, clonei seu repositório e sua aplicação não está subindo. Ela
sobe, mas quando acesso nada é exibido. Ela está atualizada? Posso me
basear nela para ver o que está acontecendo?

Em 4 de abril de 2015 21:50, Adams Alves <notifications@github.com>
escreveu:

> Ola Flavio,
>
> Fiz umas pesquisas e consegui uma solução, porem não sei se é o melhor a
> se fazer!
>
> No arquivo app/controllers/contato.js adicionei "delete req.body._id;" no
> salvaContato e consegui fazer o update. Está ok agora. Devo ter deixado
> algo de lado, já que no seu código isso não é necessário.
>
> Aqui está o repo: https://github.com/adamsalves/contatooh
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/15#issuecomment-89695100>
> .
>



-- 
Flávio Almeida
--------------------------------------------------
Caelum | Ensino e Inovação
http://www.caelum.com.br
(21) 2220-4156

Alura
www.alura.com.br

**Comment by adamsalves** [comment]
Flávio,

Clonei meu projeto e o instalei em outra pasta. Realmente estava dando o erro do mongoose(!!! MONGOOSE WARNING !!!). Estava com a versão do mongoose "3.8.25" e atualizei para a "3.8.26" e tudo ok.
Quanto aos arquivos, estão atualizados sim. É só rodar o ```grunt``` e o ```bower``` para baixar as dependências front-end. Só a raiz do projeto que não tem nada, mas as outras urls estão normais(/#/auth, /#/contatos, /contatos).

**Comment by flaviohenriquealmeida** [comment]
Eu quero te ajudar, mas não estou entendendo seu projeto, ele não condiz
com a parte em que você está no livro.

Quando abro o projeto, tem uma página em branca, até ai tudo bem, acesso o
#contato e ele exibe a tela principal. Quando clique em novo contato nada
acontece. Sequer consigo entrar na tela de cadastro.

Daí, seu problema era no _id, mas para ver isso eu tenho que interagir com
o endpoint sem ser pelo client.

Vamos combinar o seguinte, quando seu projeto estiver encaminhado eu dou
uma olhada novamente, já que você conseguiu resolver seu problema deletando
o ID, o que não deveria.

O problema é que meu tempo é curtíssimo e a demanda é muito grande, se em
cada projeto eu tenta descobrir como funciona a aplicação em seu estado
atual, eu não darei conta de todos.




Em 7 de abril de 2015 20:37, Adams Alves <notifications@github.com>
escreveu:

> Flávio,
>
> Clonei meu projeto e o instalei em outra pasta. Realmente estava dando o
> erro do mongoose(!!! MONGOOSE WARNING !!!). Estava com a versão do mongoose
> "3.8.25" e atualizei para a "3.8.26" e tudo ok.
> Quanto aos arquivos, estão atualizados sim. É só rodar o grunt e o bower
> para baixar as dependências front-end. Só a raiz do projeto que não tem
> nada, mas as outras urls estão normais(/#/auth, /#/contatos, /contatos).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/15#issuecomment-90761320>
> .
>



-- 
Flávio Almeida
--------------------------------------------------
Caelum | Ensino e Inovação
http://www.caelum.com.br
(21) 2220-4156

Alura
www.alura.com.br

**Comment by flaviohenriquealmeida** [comment]
Aliás, a parte de autenticação não funciona, vou tentar desligar e fazer o seu teste aqui.

**Comment by flaviohenriquealmeida** [comment]
Desabilitei sua parte de autenticação e fiz os testes. Tirei o seu delete
de todos os lugares. Cadastrei e alterei contatos e nenhum erro foi
impresso no console. Qual passo você está fazendo? Cadastra um, depois
volta nele e altera? Altera um já cadastrado?

Em 8 de abril de 2015 13:58, Flávio Henrique Almeida <
flaviohenriquealmeida@gmail.com> escreveu:

> Eu quero te ajudar, mas não estou entendendo seu projeto, ele não condiz
> com a parte em que você está no livro.
>
> Quando abro o projeto, tem uma página em branca, até ai tudo bem, acesso o
> #contato e ele exibe a tela principal. Quando clique em novo contato nada
> acontece. Sequer consigo entrar na tela de cadastro.
>
> Daí, seu problema era no _id, mas para ver isso eu tenho que interagir com
> o endpoint sem ser pelo client.
>
> Vamos combinar o seguinte, quando seu projeto estiver encaminhado eu dou
> uma olhada novamente, já que você conseguiu resolver seu problema deletando
> o ID, o que não deveria.
>
> O problema é que meu tempo é curtíssimo e a demanda é muito grande, se em
> cada projeto eu tenta descobrir como funciona a aplicação em seu estado
> atual, eu não darei conta de todos.
>
>
>
>
> Em 7 de abril de 2015 20:37, Adams Alves <notifications@github.com>
> escreveu:
>
>> Flávio,
>>
>> Clonei meu projeto e o instalei em outra pasta. Realmente estava dando o
>> erro do mongoose(!!! MONGOOSE WARNING !!!). Estava com a versão do mongoose
>> "3.8.25" e atualizei para a "3.8.26" e tudo ok.
>> Quanto aos arquivos, estão atualizados sim. É só rodar o grunt e o bower
>> para baixar as dependências front-end. Só a raiz do projeto que não tem
>> nada, mas as outras urls estão normais(/#/auth, /#/contatos, /contatos).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/15#issuecomment-90761320>
>> .
>>
>
>
>
> --
> Flávio Almeida
> --------------------------------------------------
> Caelum | Ensino e Inovação
> http://www.caelum.com.br
> (21) 2220-4156
>
> Alura
> www.alura.com.br
>



-- 
Flávio Almeida
--------------------------------------------------
Caelum | Ensino e Inovação
http://www.caelum.com.br
(21) 2220-4156

Alura
www.alura.com.br

**Comment by flaviohenriquealmeida** [comment]
Vou te pedir para continuarmos essas investigações no fórum, não parece ser
uma issue. O bom é que lá todo mundo sai ganhando com seu problema
compartilhado.

Este é o endereço:

https://www.facebook.com/groups/1534163683531297/

Em 8 de abril de 2015 14:09, Flávio Henrique Almeida <
flaviohenriquealmeida@gmail.com> escreveu:

> Desabilitei sua parte de autenticação e fiz os testes. Tirei o seu delete
> de todos os lugares. Cadastrei e alterei contatos e nenhum erro foi
> impresso no console. Qual passo você está fazendo? Cadastra um, depois
> volta nele e altera? Altera um já cadastrado?
>
> Em 8 de abril de 2015 13:58, Flávio Henrique Almeida <
> flaviohenriquealmeida@gmail.com> escreveu:
>
>> Eu quero te ajudar, mas não estou entendendo seu projeto, ele não condiz
>> com a parte em que você está no livro.
>>
>> Quando abro o projeto, tem uma página em branca, até ai tudo bem, acesso
>> o #contato e ele exibe a tela principal. Quando clique em novo contato nada
>> acontece. Sequer consigo entrar na tela de cadastro.
>>
>> Daí, seu problema era no _id, mas para ver isso eu tenho que interagir
>> com o endpoint sem ser pelo client.
>>
>> Vamos combinar o seguinte, quando seu projeto estiver encaminhado eu dou
>> uma olhada novamente, já que você conseguiu resolver seu problema deletando
>> o ID, o que não deveria.
>>
>> O problema é que meu tempo é curtíssimo e a demanda é muito grande, se em
>> cada projeto eu tenta descobrir como funciona a aplicação em seu estado
>> atual, eu não darei conta de todos.
>>
>>
>>
>>
>> Em 7 de abril de 2015 20:37, Adams Alves <notifications@github.com>
>> escreveu:
>>
>>> Flávio,
>>>
>>> Clonei meu projeto e o instalei em outra pasta. Realmente estava dando o
>>> erro do mongoose(!!! MONGOOSE WARNING !!!). Estava com a versão do mongoose
>>> "3.8.25" e atualizei para a "3.8.26" e tudo ok.
>>> Quanto aos arquivos, estão atualizados sim. É só rodar o grunt e o bower
>>> para baixar as dependências front-end. Só a raiz do projeto que não tem
>>> nada, mas as outras urls estão normais(/#/auth, /#/contatos, /contatos).
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/15#issuecomment-90761320>
>>> .
>>>
>>
>>
>>
>> --
>> Flávio Almeida
>> --------------------------------------------------
>> Caelum | Ensino e Inovação
>> http://www.caelum.com.br
>> (21) 2220-4156
>>
>> Alura
>> www.alura.com.br
>>
>
>
>
> --
> Flávio Almeida
> --------------------------------------------------
> Caelum | Ensino e Inovação
> http://www.caelum.com.br
> (21) 2220-4156
>
> Alura
> www.alura.com.br
>



-- 
Flávio Almeida
--------------------------------------------------
Caelum | Ensino e Inovação
http://www.caelum.com.br
(21) 2220-4156

Alura
www.alura.com.br

**Comment by adamsalves** [comment]
Ok, vou entrar no fórum.

obrigado!

**Comment by flaviohenriquealmeida** [comment]
Mas só para ficar claro para mim: você resolveu o problema com o delete e
está continuando o projeto certo? Se for, beleza... lá no forum se você
puder postar este problema que você teve para ver se outras pessoas também
tiveram. Eu não consegui replicar :(

2015-04-08 16:30 GMT-03:00 Adams Alves <notifications@github.com>:

> Ok, vou entrar no fórum.
>
> obrigado!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/15#issuecomment-91012205>
> .
>



-- 
Flávio Almeida
--------------------------------------------------
Caelum | Ensino e Inovação
http://www.caelum.com.br
(21) 2220-4156

Alura
www.alura.com.br

**Comment by adamsalves** [comment]
Sim, estou continuando sim! Tanto o meu projeto original, que comecei junto com o livro, quanto o clone que fiz do meu repo, estão funciando! O CRUD, o rest e o login estão funcinando aqui normal. Só a questão do ```delete req.body._id;``` que me intrigou... Vou colocar no fórum sim. obrigado
