### ISSUE TITLE
Cap. 12. Falha ao executar o Protractor

### ISSUE THREAD

**Issue by vinicius91carvalho** [flaviohenriquealmeida/mean-livro-codigo#16]
Fiquei quase 2 horas quebrando a cabeça para tentar descobrir o por que meus testes, após incluir as configurações de ambiente, pararam de rodar. Não consegui encontrar uma solução, então resolvi verificar no repositório oficial disponibilizado pelo Flávio, para ver se ele havia realizado algo de diferente. Foi neste momento que descobri que o projeto junto com o SauceLabs, da o mesmo problema com o Protractor.

Link: https://travis-ci.org/flaviohenriquealmeida/mean-livro-cap-12-com-saucelabs

Por que isto acontece? No livro está escrito que as alterações não deveriam impactar no funcionamento dos testes.

**Comment by flaviohenriquealmeida** [comment]
Teste unitário ou de integração?
Em 04/06/2015 22:04, "vinicius91carvalho" <notifications@github.com>
escreveu:

**Comment by flaviohenriquealmeida** [comment]
Aliás, onde está as mensagem que você recebe? Visite o fórum do Facebook
enquanto isso. Lá já tem gente fazendo Deploy. Lá fica mais fácil de
ajudar. Aqui é mais para postar issue. Só não deixe de postar o log do
travis.
Em 04/06/2015 22:21, "Flávio Henrique Almeida" <
flaviohenriquealmeida@gmail.com> escreveu:

**Comment by flaviohenriquealmeida** [comment]
Correto, o projeto sempre passou no teste do saucelabs, mas forcei um build agora e tive problemas, porém já resolvi.

É um tiro de bazuca para resolver instabilidade lá no saucelabs. Em seu protractor.js. Veja que há duas mudanças: uma chamada com promise em .get e /#/auth. 

  onPrepare: function() {
    browser.driver.get('http://localhost:3000/#/auth').then(function() {
      browser.driver.findElement(by.id('entrar')).click();
      browser.driver.findElement(by.id('login_field'))
      	.sendKeys(config.seleniumUser);
      browser.driver.findElement(by.id('password'))
      	.sendKeys(config.seleniumUserPassword);
      browser.driver.findElement(by.name('commit')).click();  
    });

Experimente a solução. Vou monitorar a situação de lá e em último caso altero o livro para incluir essa solução (que nem deveria ser aplicada).

**Comment by flaviohenriquealmeida** [comment]
Segue o link do build 
https://travis-ci.org/flaviohenriquealmeida/mean-livro-cap-12-com-saucelabs/builds/65505091

**Comment by vinicius91carvalho** [comment]
Muito obrigado pela resposta Flavio. Quando chegar em casa irei testar.

**Comment by flaviohenriquealmeida** [comment]
Tranquilo :) teste sim, vou dar um tempo. Se saucelabs não melhorar eu
adiciono essa solução no livro. Daí é só baixar a versão atualizada.
 Em 05/06/2015 10:18, "vinicius91carvalho" <notifications@github.com>
escreveu:

**Comment by vinicius91carvalho** [comment]
Muito obrigado, e parábens pelo excelente livro sobre MEAN Stack. Realmente é muito completo e até hoje não vi um livro tão completo, simples e didático. Parábens!

**Comment by flaviohenriquealmeida** [comment]
Fico contente em saber que realmente gostou. Funcionou agora?
Em 05/06/2015 21:05, "vinicius91carvalho" <notifications@github.com>
escreveu:

**Comment by vinicius91carvalho** [comment]
Sim, funcionou. Não vejo a hora de poder utilizar estes conhecimentos em meu projeto pessoal. Um detalhe, é os testes nas diretivas não estão localizados nos repositórios e que no último teste, não é abordado como testar o <meu-painel>. Eu resolvi da seguinte forma:

it('Deve mostrar o painel (Bootstrap)', function() {
        angular.element(document.body).append($element);
        expect(angular.element(document.getElementsByTagName('h3')[0]).text()).toBe('Principal');
    });

Espero que você continue fazendo este excelente trabalho. Este livro é uma obra prima. Indispensável para qualquer desenvolvedor, pois não foca somente na linguagem e frameworks, mas em novas metodologias que são muito "faladas" hoje em dia, mas estão dispersas.

**Comment by flaviohenriquealmeida** [comment]
Excelente. Vou verificar essa parte final e ver se eu entendi bem o que
ficou faltando. Vou fechar essa issue, tudo bem?  Não deixe de entrar no
grupo do livro no Facebook.

Agradeço muito seu feedback.
Em 07/06/2015 11:28, "vinicius91carvalho" <notifications@github.com>
escreveu:
