### ISSUE TITLE
Erro na execução de Testes e2e

### ISSUE THREAD

**Issue by cassiothadeu** [flaviohenriquealmeida/mean-livro-codigo#17]
Quando é executado o commando: protractor config/protractor.js

OBS: mesmo executando o exemplo do github acontece o erro..

é exibida a seguinte mensagem de erro:
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/tmp/cassiothadeu/.com.google.Chrome.Z9jCJf}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, version=43.0.2357.81, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: a338997f01368851e5355c7354b7bfa5
==== async task ====
WebDriver.findElement(By.id("entrar"))
    at exports.config.onPrepare (/home/cassiothadeu/Desktop/booksExercises/mean/contatooh/config/protractor.js:5:20)
==== async task ====
executing onPrepare
    at Function.promise (/home/cassiothadeu/.nvm/versions/node/v0.12.2/lib/node_modules/protractor/node_modules/q/q.js:650:9)
    at _fulfilled (/home/cassiothadeu/.nvm/versions/node/v0.12.2/lib/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/home/cassiothadeu/.nvm/versions/node/v0.12.2/lib/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/home/cassiothadeu/.nvm/versions/node/v0.12.2/lib/node_modules/protractor/node_modules/q/q.js:759:13)
[launcher] Process exited with error code 100

**Comment by flaviohenriquealmeida** [comment]
Você já procurou por issues aqui ou no fórum do facebook? Isso já foi resolvido. Como usamos serviços, não temos controle das mudanças realizadas neles.  Eu fiz um "workaround" para funcionar. Tanto no fórum quanto nas issues aqui resolvidas tem a solução mega hiper blaster para resolver esse problema.

**Comment by flaviohenriquealmeida** [comment]
Sobre o exemplo do Github. Ele passa no teste, basta ver o status do repositório, aliás, ele já foi modificado para resolver o problema que você apontou.

**Comment by flaviohenriquealmeida** [comment]
https://travis-ci.org/flaviohenriquealmeida/mean-livro-cap-12-com-saucelabs
Logo do travis indicando que está tudo ok.

**Comment by flaviohenriquealmeida** [comment]
Outra coisa: não estou encontrado seu repositório no github com o projeto para que eu possa ver se é outra coisa. Onde está?

**Comment by flaviohenriquealmeida** [comment]
Hum, se você está se referindo ao repositório mean-livro-cap-12-sem-saucelabs, bem, esse eu não havia aplicado o fix que resolve o problema, principalmente quem usa Windows. Já subi a alteração. Veja o que você precisa fazer olhando o diff deste commit: 

https://github.com/flaviohenriquealmeida/mean-livro-cap-12-sem-saucelabs/commit/64e1bda8bf9d4b85cccfe99c23a95765c4879f9a

Confirme para mim se está tudo ok agora para fecharmos essa issue.

**Comment by cassiothadeu** [comment]
Eu estou me referindo ao https://github.com/flaviohenriquealmeida/mean-livro-codigo/blob/master/cap-11/config/protractor.js 
que também não está funcionando, fiz as mesmas alteraçoes de acordo com a versão mean-livr-cap-12-sem-saucelabs e agora sim funcionou

**Comment by flaviohenriquealmeida** [comment]
Show. Desculpe, eu esqueci de replicar o fiz para os demais caps. Mas
funcionou certo? Se algo acontecer poste no grupo. As vezes uma alteração
no WebDriver ou no saucelabs quebra o teste.
Em 10/06/2015 19:50, "Cássio Thadeu" <notifications@github.com> escreveu:

**Comment by cassiothadeu** [comment]
Funcionou sim, Obrigado, qual o link do grupo?


Em qui, 11 de jun de 2015 às 12:28, Flavio Henrique de Souza Almeida <
notifications@github.com> escreveu:

**Comment by flaviohenriquealmeida** [comment]
Este é o link https://www.facebook.com/groups/1534163683531297/
