### ISSUE TITLE
Capitulo 7 - obtemContato por id

### ISSUE THREAD

**Issue by tborgesa** [flaviohenriquealmeida/mean-livro-codigo#18]
Flavio, primeiramente muito bom seu livro e muito ditatico... Estou feliz que so tive uma pequena duvida nesse capitulo. A duvida é a seguinte:

No controller de contato, metodo obtemContato, vc lanca um Error dentro do sucesso do promise.
Porem quando pesquiso por um id que nao existe, o server nao retorna nada, nem mesmo o erro, fica carregando.... Percebi que este erro esta em um local assincrono , mesmo porque quando coloco ele antes de consultar no Mongo volta o erro normalmente.

Meus fontes: https://github.com/tborgesa/tborgesa-contatooh

Obrigado por compartilhar o conhecimento.

**Comment by flaviohenriquealmeida** [comment]
Vou dar uma olha ainda essa semana, pode deixar e te passo o feedback.
Em 24/06/2015 10:21, "tborgesa" <notifications@github.com> escreveu:

**Comment by tborgesa** [comment]
De boa flavio... essa duvida nao impede a continuação já ate comecei o capitulo 8... heheheh

**Comment by flaviohenriquealmeida** [comment]
So para ficar claro, se você passa um Id funciona, certo? Só para eu saber
se isso vai te bloquear no andamento do livro.
Em 24/06/2015 10:25, "Flávio Henrique Almeida" <
flaviohenriquealmeida@gmail.com> escreveu:

**Comment by tborgesa** [comment]
se passo um id que existe no banco funciona
So nao funciona um id que nao tenha no banco... nao impede nao

**Comment by flaviohenriquealmeida** [comment]
Como você está enviando um ID que não existe? Qual o teste que você está
fazendo? Você está forçando um ID errado no Angular?

Em 24 de junho de 2015 10:44, tborgesa <notifications@github.com> escreveu:

> se passo um id que existe no banco funciona
> So nao funciona um id que nao tenha no banco... nao impede nao
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/18#issuecomment-114872245>
> .
>



-- 
Flávio Almeida
--------------------------------------------------
Caelum | Ensino e Inovação
http://www.caelum.com.br
(21) 2220-4156

Alura
www.alura.com.br

**Comment by flaviohenriquealmeida** [comment]
Acabei de fazer o teste assim: abri um contato que não existe, digitando na
URL um ID inválido. Recebo corretamente a mensagem de erro do servidor
dizendo que o contato não existe. É esse o seu teste?

Em 24 de junho de 2015 11:06, Flávio Henrique Almeida <
flaviohenriquealmeida@gmail.com> escreveu:

> Como você está enviando um ID que não existe? Qual o teste que você está
> fazendo? Você está forçando um ID errado no Angular?
>
> Em 24 de junho de 2015 10:44, tborgesa <notifications@github.com>
> escreveu:
>
>> se passo um id que existe no banco funciona
>> So nao funciona um id que nao tenha no banco... nao impede nao
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/18#issuecomment-114872245>
>> .
>>
>
>
>
> --
> Flávio Almeida
> --------------------------------------------------
> Caelum | Ensino e Inovação
> http://www.caelum.com.br
> (21) 2220-4156
>
> Alura
> www.alura.com.br
>



-- 
Flávio Almeida
--------------------------------------------------
Caelum | Ensino e Inovação
http://www.caelum.com.br
(21) 2220-4156

Alura
www.alura.com.br

**Comment by flaviohenriquealmeida** [comment]
Vi seu repositório, você trocou o código de erro para 500. Era para ser
404. Dá uma olhada no `contato.js`. Volte para 404 e veja se funciona.
Ainda assim, tem algo que preciso rever, mas primeiro faz funcionar.

Em 24 de junho de 2015 11:07, Flávio Henrique Almeida <
flaviohenriquealmeida@gmail.com> escreveu:

> Acabei de fazer o teste assim: abri um contato que não existe, digitando
> na URL um ID inválido. Recebo corretamente a mensagem de erro do servidor
> dizendo que o contato não existe. É esse o seu teste?
>
> Em 24 de junho de 2015 11:06, Flávio Henrique Almeida <
> flaviohenriquealmeida@gmail.com> escreveu:
>
>> Como você está enviando um ID que não existe? Qual o teste que você está
>> fazendo? Você está forçando um ID errado no Angular?
>>
>> Em 24 de junho de 2015 10:44, tborgesa <notifications@github.com>
>> escreveu:
>>
>>> se passo um id que existe no banco funciona
>>> So nao funciona um id que nao tenha no banco... nao impede nao
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/18#issuecomment-114872245>
>>> .
>>>
>>
>>
>>
>> --
>> Flávio Almeida
>> --------------------------------------------------
>> Caelum | Ensino e Inovação
>> http://www.caelum.com.br
>> (21) 2220-4156
>>
>> Alura
>> www.alura.com.br
>>
>
>
>
> --
> Flávio Almeida
> --------------------------------------------------
> Caelum | Ensino e Inovação
> http://www.caelum.com.br
> (21) 2220-4156
>
> Alura
> www.alura.com.br
>



-- 
Flávio Almeida
--------------------------------------------------
Caelum | Ensino e Inovação
http://www.caelum.com.br
(21) 2220-4156

Alura
www.alura.com.br

**Comment by tborgesa** [comment]
Entao Flavio... estou na empresa e comecei a instalar o mongo aqui. So que no momento de complilar o bson ta dando um erro de rede aqui: 400 status code downloading tarball

Eh alguma coisa do proxy. Se nao conseguir verificar o erro aqui anoite te passo um feedBack la de casa. Muito obrigado pela agilidade.

**Comment by flaviohenriquealmeida** [comment]
Beleza, sem pressa. Fico aguardando seu feedback então.

Em 24 de junho de 2015 12:32, tborgesa <notifications@github.com> escreveu:

> Entao Flavio... estou na empresa e comecei a instalar o mongo aqui. So que
> no momento de complilar o bson ta dando um erro de rede aqui: 400 status
> code downloading tarball
>
> Eh alguma coisa do proxy. Se nao conseguir verificar o erro aqui anoite te
> passo um feedBack la de casa. Muito obrigado pela agilidade.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/18#issuecomment-114912402>
> .
>



-- 
Flávio Almeida
--------------------------------------------------
Caelum | Ensino e Inovação
http://www.caelum.com.br
(21) 2220-4156

Alura
www.alura.com.br

**Comment by tborgesa** [comment]
Entao Flavio... Esse ero na hora de compilar o bson: "400 status code downloading tarball" e para fazer o download no node "http://nodejs.org/dist/v0.12.4/node-v0.12.4.tar.gz".

Mas qd coloco essa url no navegador ele faz download normalmente... Voce ja passou por esse erro: Veja o conteudo do arquivo "node_modules\mongodb\node_modules\bson\builderror.log":

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 400 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:247:14)
gyp ERR! stack     at Request.emit (events.js:129:20)
gyp ERR! stack     at Request.onRequestResponse (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1156:10)
gyp ERR! stack     at ClientRequest.emit (events.js:107:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:426:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:317:20)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:163:16)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:126:10)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk\capitulo7\node_modules\mongodb\node_modules\bson
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 

Continuo na buscando uma solução, mas se tiver alguma dica ja ajuda. hehehe

**Comment by flaviohenriquealmeida** [comment]
BSON na plataforma windows não rola compilação, ele faz fallback no driver
em JS. Isso é esperado no Windows, mas não vi a mensagem alegando que ele
fez fallback no driver em JavaScript. Em teoria, mesmo com esse erro, deve
passar (mas o erro está diferente do que eu costumo ver na plataforma
Windows).

Em 24 de junho de 2015 13:49, tborgesa <notifications@github.com> escreveu:

> Entao Flavio... Esse ero na hora de compilar o bson: "400 status code
> downloading tarball" e para fazer o download no node "
> http://nodejs.org/dist/v0.12.4/node-v0.12.4.tar.gz".
>
> Mas qd coloco essa url no navegador ele faz download normalmente... Voce
> ja passou por esse erro: Veja o conteudo do arquivo
> "node_modules\mongodb\node_modules\bson\builderror.log":
>
> gyp WARN install got an error, rolling back install
> gyp ERR! configure error
> gyp ERR! stack Error: 400 status code downloading tarball
> gyp ERR! stack at Request. (C:\Program
> Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:247:14)
> gyp ERR! stack at Request.emit (events.js:129:20)
> gyp ERR! stack at Request.onRequestResponse (C:\Program
> Files\nodejs\node_modules\npm\node_modules\request\request.js:1156:10)
> gyp ERR! stack at ClientRequest.emit (events.js:107:17)
> gyp ERR! stack at HTTPParser.parserOnIncomingClient
> (_http_client.js:426:21)
> gyp ERR! stack at HTTPParser.parserOnHeadersComplete
> (_http_common.js:111:23)
> gyp ERR! stack at Socket.socketOnData (_http_client.js:317:20)
> gyp ERR! stack at Socket.emit (events.js:107:17)
> gyp ERR! stack at readableAddChunk (_stream_readable.js:163:16)
> gyp ERR! stack at Socket.Readable.push (_stream_readable.js:126:10)
> gyp ERR! System Windows_NT 6.3.9600
> gyp ERR! command "node" "C:\Program
> Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js"
> "rebuild"
> gyp ERR! cwd
> E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk\capitulo7\node_modules\mongodb\node_modules\bson
> gyp ERR! node -v v0.12.4
> gyp ERR! node-gyp -v v1.0.3
> gyp ERR! not ok
>
> Continuo na buscando uma solução, mas se tiver alguma dica ja ajuda. hehehe
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/18#issuecomment-114939335>
> .
>



-- 
Flávio Almeida
--------------------------------------------------
Caelum | Ensino e Inovação
http://www.caelum.com.br
(21) 2220-4156

Alura
www.alura.com.br

**Comment by tborgesa** [comment]
Entao esse eh o erro que pego na hora do npm install para baixar os pacotes

Se subir o server da o seguinte erro:

.E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk\capitulo7\node_modules\mongo
ose\node_modules\mongodb\lib\mongodb\connection\base.js:246
        throw message;
              ^
TypeError: Cannot read property 'length' of undefined
    at processResults (E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk\capit
ulo7\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1581:31)
    at E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk\capitulo7\node_module
s\mongoose\node_modules\mongodb\lib\mongodb\db.js:1619:20
    at E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk\capitulo7\node_module
s\mongoose\node_modules\mongodb\lib\mongodb\db.js:1157:7
    at E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk\capitulo7\node_module
s\mongoose\node_modules\mongodb\lib\mongodb\db.js:1890:9
    at Server.Base._callHandler (E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\t
runk\capitulo7\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection
\base.js:448:41)
    at E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk\capitulo7\node_module
s\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:481:18
    at MongoReply.parseBody (E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk
\capitulo7\node_modules\mongoose\node_modules\mongodb\lib\mongodb\responses\mong
o_reply.js:68:5)
    at null.<anonymous> (E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk\cap
itulo7\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.
js:439:20)
    at emit (events.js:107:17)
    at null.<anonymous> (E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk\cap
itulo7\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connect
ion_pool.js:201:13)
24 Jun 14:02:54 - [nodemon] app crashed - waiting for file changes before starti
ng...

**Comment by flaviohenriquealmeida** [comment]
Você está usando provavelmente uma versão do MongoDB que não é a do livro,
talvez a mais nova e está usando o mongoose que indico no livro, que é para
a versão 3.

Sugiro que a gente feche essa issue aqui, pois não tem relação com o livro
e você abra essas dúvidas lá no fórum. Se continuarmos aqui vão achar que é
issue com o código do livro o que não é realmente,

2015-06-24 14:03 GMT-03:00 tborgesa <notifications@github.com>:

> Entao esse eh o erro que pego na hora do npm install para baixar os pacotes
>
> Se subir o server da o seguinte erro:
>
>
> .E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk\capitulo7\node_modules\mongo
> ose\node_modules\mongodb\lib\mongodb\connection\base.js:246
> throw message;
> ^
> TypeError: Cannot read property 'length' of undefined
> at processResults
> (E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk\capit
> ulo7\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1581:31)
> at
> E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk\capitulo7\node_module
> s\mongoose\node_modules\mongodb\lib\mongodb\db.js:1619:20
> at
> E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk\capitulo7\node_module
> s\mongoose\node_modules\mongodb\lib\mongodb\db.js:1157:7
> at
> E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk\capitulo7\node_module
> s\mongoose\node_modules\mongodb\lib\mongodb\db.js:1890:9
> at Server.Base._callHandler
> (E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\t
>
> runk\capitulo7\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection
> \base.js:448:41)
> at
> E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk\capitulo7\node_module
> s\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:481:18
> at MongoReply.parseBody
> (E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk
>
> \capitulo7\node_modules\mongoose\node_modules\mongodb\lib\mongodb\responses\mong
> o_reply.js:68:5)
> at null. (E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk\cap
>
> itulo7\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.
> js:439:20)
> at emit (events.js:107:17)
> at null. (E:\Pessoal\GitHub\tborgesa\tborgesa-contatooh\trunk\cap
>
> itulo7\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connect
> ion_pool.js:201:13)
> 24 Jun 14:02:54 - [nodemon] app crashed - waiting for file changes before
> starti
> ng...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/18#issuecomment-114942670>
> .
>



-- 
Flávio Almeida
--------------------------------------------------
Caelum | Ensino e Inovação
http://www.caelum.com.br
(21) 2220-4156

Alura
www.alura.com.br

**Comment by tborgesa** [comment]
ok.. entao vamos so encerrar esse assunto e esperar o feedback anoite do erro no controller... vou instalar aqui o mongoDB do livro... na hora de fazer download devo ter pego a mis nova.

**Comment by flaviohenriquealmeida** [comment]
Você pode fazer o seguinte: fique com o mongo mais novo, mas remove o
mongoose e instala sem a versão. Ele baixará a mais nova e vai funcionar.
Aguardo seu feedback à noite.

Em 24 de junho de 2015 14:13, tborgesa <notifications@github.com> escreveu:

> ok.. entao vamos so encerrar esse assunto e esperar o feedback anoite do
> erro no controller... vou instalar aqui o mongoDB do livro... na hora de
> fazer download devo ter pego a mis nova.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/18#issuecomment-114944711>
> .
>



-- 
Flávio Almeida
--------------------------------------------------
Caelum | Ensino e Inovação
http://www.caelum.com.br
(21) 2220-4156

Alura
www.alura.com.br

**Comment by tborgesa** [comment]
Flavio, consegui fazer o sistema rodar novamente... mas voltando ao erro inicial do metodo de busca por id...

mesmo colocando o codigo 404 na segunda funcao do then deu erro.

Mas vamos as peculariedades. Estou testando apenas o backEnd pelo PostMan.... para nao ter a influencia do Angular (frontEnd)

Tenho um contato cadastrado com o id 558afaa4f0c04b44120399f5

portanto essa url localhost:3007/contatos/558afaa4f0c04b44120399f5 me retorna esse id.

Caso eu coloque algo nada a ver como dbsher

esse url localhost:3007/contatos/dbsher me retorna o erro 404 pois cai na segunda function do metodo.

Mas caso coloque um id parecido como 558afaa4f0c04b44120399f6

essa url localhost:3007/contatos/ 558afaa4f0c04b44120399f6 cai no primeira function e ai ocorre que nao volta nada para o servidor... espero que esses detalhes ajude.. desculpe o incomodo.

**Comment by tborgesa** [comment]
Deletei os comentarios que nao sao perninentes ao assunto para nao confundir quem estiver conbsultando, se quiser deletar os seus.

**Comment by flaviohenriquealmeida** [comment]
Com angular funciona?
Em 24/06/2015 16:05, "tborgesa" <notifications@github.com> escreveu:

**Comment by flaviohenriquealmeida** [comment]
Se não quiser esperar, da uma olhada no gabarito do projeto e teste em sua
máquina.  Aqui funcionou liso. Pode outro ponto do seu código.
Em 24/06/2015 17:17, "Flávio Henrique Almeida" <
flaviohenriquealmeida@gmail.com> escreveu:

**Comment by flaviohenriquealmeida** [comment]
Como não consigo replicar seu problema no código original, viu fechar essa
issue e continuamos no fórum.
Em 24/06/2015 17:20, "Flávio Henrique Almeida" <
flaviohenriquealmeida@gmail.com> escreveu:

**Comment by flaviohenriquealmeida** [comment]
Atualiza seu repo que final de semana eu clono para tentar replicar. Me dá
ok quando tiver atualizado.
Em 24/06/2015 17:23, "Flávio Henrique Almeida" <
flaviohenriquealmeida@gmail.com> escreveu:

**Comment by tborgesa** [comment]
Pelo angular tb nao funciona... so tirei o angular dos meus testes para diminiuir o contexto do teste.

Vou clonar seu projeto e roda-lo hoje a noite e quando atualizar o meu projeto te aviso. Muito obrigado pela atenção.

**Comment by tborgesa** [comment]
Flavio... mas uma vez incomodando... hehehe...

Fiz um clone deste projeto e subi o server do capitulo 4...

Deu o mesmo erro do meu, veja pela figura abaixo... o id final "a" deu sucesso (status 304)... porem o de final "b" ficou pendente... percebi que caso o contato seja null e entre no if nao e retornado nada para a aplicacao... apenas lancado a excecao... (linha 27 do controller de contato.)

![capturar](https://cloud.githubusercontent.com/assets/10090401/8343664/3426588e-1aae-11e5-9e37-0949f617815c.PNG)
