### ISSUE TITLE
Não consigo achar a sua pasta APP - models 

### ISSUE THREAD

**Issue by HugoOliveiraThor** [flaviohenriquealmeida/mean-livro-codigo#19]
Boa Tarde Flávio , não consigo achar sua pasta App.Models que voce aplica no curso .
Estou com um problema pois o meu server não consegue radar pois acusa que não consegue localizar o app.controllers.contato ;
![erro](https://cloud.githubusercontent.com/assets/8323470/8606275/e277dee0-2660-11e5-80bc-bfcd1e85f493.png)

Segue meu código . 

![controllercontato](https://cloud.githubusercontent.com/assets/8323470/8606345/646e8386-2661-11e5-892f-ec2de161049a.png)
![express](https://cloud.githubusercontent.com/assets/8323470/8606348/647251e6-2661-11e5-9b76-2e4e4a7441de.png)
![modelscontato](https://cloud.githubusercontent.com/assets/8323470/8606346/647028f8-2661-11e5-8a3f-ccef3f919494.png)
![routescontato](https://cloud.githubusercontent.com/assets/8323470/8606347/64706070-2661-11e5-9ab6-1e75c0790036.png)
Veja se consegue me ajudar . 
Muito Obrigado !

**Comment by flaviohenriquealmeida** [comment]
Oi Hugo, aqui é um repositório do Git. Dúvidas assim ficam no fórum do facebook. Abre lá a dúvida no fórum do facebook e vou fechar aqui.

https://www.facebook.com/groups/1534163683531297/

**Comment by flaviohenriquealmeida** [comment]
Você ainda pode comparar seu código com o gabarito que está no meu repositório.

**Comment by flaviohenriquealmeida** [comment]
Só para não deixar você sem resposta, você adicionou o código de controllers/contato.js dentro de models/contato.js. Não faz sentido um model usar um controller, é um controller que deve usar um model.

**Comment by HugoOliveiraThor** [comment]
Flávio muito obrigado eu não sei porque coloquei o mesmo código do routes
contato dentro de Model. Você é o cara!

Em quinta-feira, 9 de julho de 2015, Flavio Henrique de Souza Almeida <
notifications@github.com> escreveu:

> Só para não deixar você sem resposta, você adicionou o código de
> controllers/contato.js dentro de models/contato.js. Não faz sentido um
> model usar um controller, é um controller que deve usar um model.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/19#issuecomment-120139996>
> .
>


-- 
*Hugo Henrique Silva Oliveira*
