### ISSUE TITLE
Pasta vendor faltando

### ISSUE THREAD

**Issue by pedrohills** [flaviohenriquealmeida/mean-livro-codigo#2]
Não sei se precisaria ter, mas a pasta vendor não está na pasta public.

**Comment by coreilabs** [comment]
o bower cria ela automaticamente depois que vc configura o .bowerrc

**Comment by flaviohenriquealmeida** [comment]
Isso mesmo! Precisa configurar no .bowerrc. Em breve estarei subindo os próximos capítulos. Inclusive já teremos uma atualização do livro que poderá ser baixando assim que o link de vocês estiver atualizado. Abraço!

**Comment by coreilabs** [comment]
n entendi muito bem como vou baixar essa atualização @flaviohenriquealmeida 
parabéns pelo trabalho véi!

**Comment by flaviohenriquealmeida** [comment]
Obrigado! O link que vc baixa o livro  será atualizado!
