### ISSUE TITLE
Bootstrap Glyphicon não carrega após minificação Cap. 10

### ISSUE THREAD

**Issue by gmobilsistemas** [flaviohenriquealmeida/mean-livro-codigo#20]
Bom dia, estou lendo o livro e concluí o capítulo 10. No arquivo public/partials/contatos.html tenho um ícone juntamente com o campo search da lista de contatos:

```html
<div class="input-group">
	<span class="input-group-addon">
		<span class="glyphicon glyphicon-search"></span>
	</span>
	<input type="search" class="form-control" ng-model="filtro" placeholder="pesquisar por parte do nome">
</div>
```
Após realizar a minificação com o Grunt e subir a aplicação dentro da dist, o ícone não carrega na tela. Poderia me ajudar a resolver este problema?

**Comment by flaviohenriquealmeida** [comment]
Olá, aqui é um repositório para postar issues do livro, no seu caso, como é uma novidade, uma melhoria, o lugar mais recomendado para pedir ajuda é no nosso fórum do facebook. Segue o link. 

https://www.facebook.com/groups/1534163683531297/

Vou fechar issue e excluí-la, já que não é uma issue do livro.

**Comment by flaviohenriquealmeida** [comment]
Aliás, quando for reportar lá no fórum, compartilhe seu repositório do github com seu código para que todos possam ver e ajudar.
