### ISSUE TITLE
Cap 5.12

### ISSUE THREAD

**Issue by felipechama** [flaviohenriquealmeida/mean-livro-codigo#21]
O script está apresentando erro 500 e quando fui debugar (dando console.log em cada parte do script) identifiquei que ele não está passando undefined em req.body. 

Assim que envio os dados ele não consegue pegar os dados do formulário para criar um novo usuário ou alterá-lo. Como resolver?

**Comment by felipechama** [comment]
Por esse motivo gera o erro "Cannot read property '_id' of undefined".

**Comment by felipechama** [comment]
Comparei os arquivos com seu repositório e nada! Erro 500 ainda :/
Se puder me ajudar: https://github.com/felipechama/livro-mean

**Comment by flaviohenriquealmeida** [comment]
Você comparou, mas rodou o gabarito em sua máquina? Já aconteceu de compararem e ainda ter algo faltando.  Se você baixar o repo e funcionar, eu fecho aqui e você abre no grupo do Facebook.  Aqui fica issues mesmo. Só vou poder olhar seu repo na outra semana.

**Comment by flaviohenriquealmeida** [comment]
Olhei seu repo e de cara vi que seu Express está sem alguns midlewares que peço para adicionar como bodyparser.

**Comment by flaviohenriquealmeida** [comment]
A configuração que ficou faltando é feita no cap 02 e envolve o express.js.

**Comment by flaviohenriquealmeida** [comment]
Ah, Felipe, quero o link final da aplicação deployada no openshift! Hehehe. Sucesso e bom estudo.

**Comment by felipechama** [comment]
Puts! Valeu pela ajuda. Estou lendo cada página e não sei porque acabei pulando essa parte. Obrigado pela ajuda e parabéns pelo livro, muito claro e didático. Qual o grupo do facebook? Abs
