### ISSUE TITLE
rhc tail contatooh Cap. 14 Deploy

### ISSUE THREAD

**Issue by IgorVieira** [flaviohenriquealmeida/mean-livro-codigo#22]
Professor, estou na fase final do livro, partindo para o deploy, mas encontro algumas dificuldades, assim que eu executo o comando - sudo rhc tail contatooh - para realizar a leitura continua do arquivo de log da aplicação, ele me apresenta erros relacionados a forma como inicializo o servidor, ele mostra a seguinte mensagem:

Warning: express.createServer() is deprecated, express
applications no longer inherit from http.Server,
please use:
  var express = require("express");
  var app = express();

Tentei buscar algumas soluções, verifiquei se era o arquivo .travis.yml ou package.json, mas nada, até então minha aplicação havia passado em todos os testes, mas pouco antes do deploy,  sempre antes do bendito deploy kkkk aconteceu esse erro, desde já agradeço a atenção.

**Comment by flaviohenriquealmeida** [comment]
Essa mensagem não tem relação com sua App, mas com a infra do openshift que usa em algum ponto o Express. Mesmo com esse warning sua App funcionará normal.Olhe o arquivo de log do travis que com certeza você encontrará a causa.

Aliás, esse não é aquele problema que o donain estava errado no seu .travis.um? 

Confirme para mim para que eu possa fechar essa issue.

**Comment by flaviohenriquealmeida** [comment]
Aliás, dei a dica para verificar sua App cadastrada no github.

**Comment by IgorVieira** [comment]
Sim era um erro no domain,  mas foi corrigido, e quanto a aplicação eu setei novamente os tokens de autenticação, porém ele autentica, no entanto  não redireciona, fiz o teste com mais uma conta e nada

**Comment by flaviohenriquealmeida** [comment]
Ótima oportunidade para pedir ajuda no fórum. Eu me loguei na sua app e seu
server deu internal server erro. Você notou? Verifique seu código que
configura o passport e que usa as variáveis de ambiente.
Em 04/09/2015 03:23, "Igor Vieira" <notifications@github.com> escreveu:

**Comment by IgorVieira** [comment]
Erros corrigidos, tanto a autenticação da aplicação quanto o erro no arquivo  ./conf/env/production.js que no qual estava escrito MONGO_DB e não MONGODB_DB e reescrita do arquivo passport para setar as configurações de domínio

**Comment by flaviohenriquealmeida** [comment]
Fez o deploy, parabéns! Você passou por um batismo de fogo no mundo Node.js. Aprendeu Angular, Express, MongoDB, teste unitário, teste de integração, integração continua, automação de tarefas, segurança, bootstrap, deploy. Consagração máxima!
