### ISSUE TITLE
Cap 12 - falha no teste e2e

### ISSUE THREAD

**Issue by Lysandroc** [flaviohenriquealmeida/mean-livro-codigo#23]
Olá, Flavio

Estou com um problema ao fazer os testes no sauce labs, 
o travis do meu projeto está apresentando um estranho, já fiz varias modificações no projeto e gostaria muito de continuar a leitura com a pratica do livro. 

Um dos screencast do meu sauce labs
![0002screenshot](https://cloud.githubusercontent.com/assets/8335018/9707791/6561205e-54e8-11e5-9cc8-8ece3405d745.png)

Segue o travis do meu projeto.
https://travis-ci.org/Lysandroc/contatooh

Gostaria também de parabeniza-lo pelo excelente livro, nunca vi algo igual.

**Comment by flaviohenriquealmeida** [comment]
Olá, uma issue já havia resolvido este problema peculiar no saucelabs. Postei a solução no forum:
https://www.facebook.com/groups/1534163683531297/

**Comment by flaviohenriquealmeida** [comment]
Eu fechei a issue, se continuar, eu reabro. ok? Obrigado pelo feedback do livro!
