### ISSUE TITLE
Errata Capítulo 2

### ISSUE THREAD

**Issue by ericdouglas** [flaviohenriquealmeida/mean-livro-codigo#3]
## Página 20

No livro está assim:

```js
// config/express.js
var home = require( './app/routes/home' );
```

e o correto é assim:

```js
var home = require( '../app/routes/home' );
```

## Página 23

No livro está assim:
```js
// app/routes/home.js
var controller = require( './app/controller/home' );
```

e o correto é assim:

```js
var controller = require( '../controllers/home' )();
```

**Comment by coreilabs** [comment]
hehehe tbm encontrei, mas to muito entusiasmado com esse livro

**Comment by flaviohenriquealmeida** [comment]
Pessoal, já corrigi esse bug no livro. Não se preocupem, quando ele entrar no express-load não vai precisar usar require. Aliás, estou refatorando a parte de autenticação colocando uma novidade: ela usará interceptadores do AngularJS. Decidi fazer isso para deixar mais claro e ainda mais profissional a parte de autenticação. O código que vou subir do cap 08 já será dessa forma tudo bem? Daqui a uma semana o link de vocês estará atualizado para abaixar a nova versão!!

**Comment by ericdouglas** [comment]
Legal @flaviohenriquealmeida ! :smile:
