### ISSUE TITLE
Problemas com capítulo 5. 

### ISSUE THREAD

**Issue by tibernardinelli** [flaviohenriquealmeida/mean-livro-codigo#4]
Flavio,

Encontrei um problema na hora de configurar as rotas do método delete, o angular fez a chamada para /contatos?id=x ao invés de /contatos/x, o que gerou um 404. configurando a rota da seguinte maneira funcionou:

```javascript
//app/routes/contato.js
module.exports = function(app){
	var controller = app.controllers.contato;

	app.route('/contatos')
		.get(controller.listaContato)
		.post(controller.salvaContato)
                .delete(controller.removeContato);
	app.route('/contatos/:id')
		.get(controller.obtemContato)
		.delete(controller.removeContato);
};
```

Tem alguma configuração diferente para funcionar como estava no livro?

Att.

**Comment by flaviohenriquealmeida** [comment]
Olá! Deve funcionar como está no livro. Aliás, compare seu código com o gabarito aqui no github. Mas se o seu código está com este comportamento, tem como você compartilhar seu ContatoController para que eu possa dar uma olhada no seu código? A gente descobre o que é :)

**Comment by flaviohenriquealmeida** [comment]
Melhor ainda, se puder compartilhar seu projeto até o cap 05 fica melhor :)

**Comment by tibernardinelli** [comment]
Acredito que eu passei batido em alguma coisa, rs... 

https://github.com/tibernardinelli/contatooh

**Comment by tibernardinelli** [comment]
Alias, estou gostando MUITO do livro! Parabéns!! não conhecia o angular.js, não vejo a hora de usa-lo pra valer!

**Comment by tibernardinelli** [comment]
Descobri o que aconteceu..

```javascript
		var Contatos = $resource("/contatos");
		
		function buscaContato(){
			Contatos.query(
				function(data){
					$scope.contatos = data;
				},
				function(statusText) {
					console.log("Bãã"),
					console.log(statusText)
				}
			);
		}
		buscaContato();

	    var Contato = $resource("/contatos/:id");
		$scope.remove = function (contato){
			Contato.remove({id: contato._id},			
				buscaContato,
				function(erro){
					console.log('Não foi possível remover contato');
					console.log(erro);
				});
		}
````

Um resource atende a /contatos e outro para /contatos/:id, para o remove funcionar é necessário usar o /contatos/:id... como faço no express para obter os queryparameters? por exemplo ?id=x...

**Comment by flaviohenriquealmeida** [comment]
Olá! A boa notícia é que você não errou nada e a segunda boa notícia é que você descobriu um erro de digitação na apostila! O problema esta na linha:

```
var Contato = $resource("/contatos");
```

Ela deve ser : 

```
var Contato = $resource("/contatos/:id");
```

Quando você migra para serviço, o código está certo. É por isso que até agora ninguém havia reportado. Muito obrigado. Teste e me dê um feedback!

**Comment by flaviohenriquealmeida** [comment]
Fico MUITO feliz em saber que você está gostando do livro. Eu escrevi pensando em quem está começando, mas sem esquecer o cara que já sabe. Qualquer coisa pode reportar aqui. Abração!

**Comment by tibernardinelli** [comment]
Perfeito, funciona! mas isso não significa apontar para uma nova rota? afinal de contas uma rota tem e a outra não... 

Eu sou desenvolvedor a 7 anos. comecei com Delphi (eca), passei para java, depois python e agora .net. Mas sempre, sempre foquei no back-end e sou um zero a esquerda para o front... com relação ao node sou apenas um entusiasta, adoro brincar com isso!!

```javascript
		$routeProvider.when('/contatos',{
			templateUrl: "partials/contatos.html",
			controller: "ContatosController"
		});
		$routeProvider.when('/contato/:contatoId',{
			templateUrl: "partials/contato.html",
			controller: "ContatoController"
		});
```

**Comment by flaviohenriquealmeida** [comment]
A rota é a mesma /contatos/ porém o padrão REST utiliza o verbo HTTP para saber se é um post, delete, get ou put. No caso da deleção, o AngularJS usa o verbo DELETE. Daí, temos uma rota reparada para este verbo + o nome da rota. Só que essa rota recebe um parâmetro. Por exemplo, se tivéssemos duas rotas do verbo POST, mas uma recebe parâmetro e outra não, o Express saberá diferenciar. Não sei se fui claro (pela hora da noite). Mas o critério de seleção de uma rota é:

VERBO HTTP + URL + PARÂMETROS

Era essa sua dúvida, ou passei batido?

**Comment by flaviohenriquealmeida** [comment]
Uma coisa que pode confundir, é que a rota no AngularJS é uma e no Express é outra. A do primeiro serve para indicar qual HTML ele deve baixar do servidor via ajax e mesclar com o HTML index.html que nunca recarrega. A do segundo, é a que efetivamente traz os dados.

**Comment by flaviohenriquealmeida** [comment]
ah, só deixando claro. Vc usa $resource('/contatos/:id') tanto para a rota que lista quando para a rota que adiciona, altera ou deleta. O angular é esperto para saber como montará a URL para a rota do servidor. Resumindo: em seu controller você terá apenas um `var Contato = $resource('/contatos/:id'); que será usado para todos os casos daquele CRUD. Lembre-se que em $resource, é uma rota para o servidor, não é a rota para parciais do angular definidas no main.js

**Comment by tibernardinelli** [comment]
Agora entendi!! Obrigado Flavio!

**Comment by flaviohenriquealmeida** [comment]
Se ainda pairar alguma dúvida, eu vou respondendo com calma. Ë que estou morto agora e quando fico cansado eu fico muito verboso nas explicações. :) Aliás, o livro deve ser atualizado amanhã com todas as correções até o momento, inclusive a sua contribuição! :)

**Comment by coreilabs** [comment]
irrrul!!! mto bom!

**Comment by flaviohenriquealmeida** [comment]
tibernardinelli, tudo bem até agora?
