### ISSUE TITLE
Não estou conseguindo iniciar o servidor

### ISSUE THREAD

**Issue by devthiagolino** [flaviohenriquealmeida/mean-livro-codigo#5]
![error_nodejs](https://cloud.githubusercontent.com/assets/6722366/5825758/91e7ba14-a0cc-11e4-9ef5-d519cb966f2d.png)

Toda vez que tento executar o node server eu tenho esse monte de erros. Alguém conseguiu executar normalmente? Alguém sabe me informar o que é isso?

**Comment by devthiagolino** [comment]
Gente, eu peço perdão pois foi uma desatenção minha. O erro estava ocorrendo devido a seguinte linha de código:

Deve ser assim:

app.set('view engine', 'ejs');
app.set('views', './app/views');  

E no meu código estava ao invés do "set" o "use".
Perdão :)!

**Comment by flaviohenriquealmeida** [comment]
Oi Tiago.  Sem problemas. Vc está com o PDF atualizado?
Em 20/01/2015 18:56, "Thiago Lino" <notifications@github.com> escreveu:

**Comment by devthiagolino** [comment]
Cara, fiz o download ontem, já estava atualizado?

**Comment by flaviohenriquealmeida** [comment]
Não.  Só hoje. :)
Em 20/01/2015 22:15, "Thiago Lino" <notifications@github.com> escreveu:

**Comment by devthiagolino** [comment]
Como faço pra ter a versão atualizada?

**Comment by flaviohenriquealmeida** [comment]
Olá Thiago! Se não estou enganado, o link que você baixa o livro é atualizado. Baixe-o novamente. Se no CAP 08 tiver a seção (Interceptadores do Angular) ele está atualizado.
