### ISSUE TITLE
Servidor travou ao tentar acessar http://localhost:3000/

### ISSUE THREAD

**Issue by devthiagolino** [flaviohenriquealmeida/mean-livro-codigo#6]
![error_nodejs](https://cloud.githubusercontent.com/assets/6722366/5826051/8f27a904-a0ce-11e4-820c-b2e147f8031e.png)
 Galera, agora eu teoricamente consegui iniciar o servidor, mas estou tendo problemas, acho que estouro de memória, sei que minha máquina está travando, e está apresentando esse erro:

FATAL ERROR: JS Alocation...

Alguém?

**Comment by flaviohenriquealmeida** [comment]
Bizarro. Só para teste, tente rodar seu terminal com administrador. Se não
der jeito, tente desinstalar o node. Se reinstalar e der pau. Tente uma
versão anterior.
Em 20/01/2015 19:04, "Thiago Lino" <notifications@github.com> escreveu:

**Comment by devthiagolino** [comment]
Blz. Vou tentar e aviso.

**Comment by devthiagolino** [comment]
Eu acredito que foi alguma "mopa" na instalação ou dependências no node no windows, sei lá, eu fiz os mesmos testes no meu Ubuntu e funfou.

Mas estou com uma dúvida, porque eu consigo acessar:
localhost:3000/index, vai pra view normalmente,
mas ao tentar acessar, localhost:3000/ ele remove a barra e rendeiriza o index.html que está dentro de public. Alguma sugestão?

**Comment by flaviohenriquealmeida** [comment]
Em qual seção do livro você parou quando isso aconteceu? Já experimentou fazer a mesma coisa com o gabarito deste repositório?
