### ISSUE TITLE
Diretiva ngOptions

### ISSUE THREAD

**Issue by Dhenner** [flaviohenriquealmeida/mean-livro-codigo#7]
No capitulo 7 modulo 14, o codigo html demonstrado não funcionou, olhando na documentação da diretiva a mesma deve estar dentro da TAG select para exibir seus valores indicados, onde no livro esta dentro da TAG.

**Comment by flaviohenriquealmeida** [comment]
Dhenner, você está com a versão atualizada com as erratas? Saiu ontem. Sugiro que baixe novamente. Havia um typo neste HTML.

**Comment by flaviohenriquealmeida** [comment]
Deve ser assim:

```
  <select id="emergencia" 
	      class="form-control"
	      ng-model="contato.emergencia"
	      ng-options=
	        "contato._id as contato.nome for contato in contatos"> 
	  </select>
```

O que condiz com o fiddle da própria equipe do AngularJS: http://jsfiddle.net/qWzTb/

**Comment by flaviohenriquealmeida** [comment]
Como saber se o seu livro está atualizado? No CAP 08 tem a seção "Interceptadores do AngularJS".

**Comment by Dhenner** [comment]
Boa tarde,
como posso baixar a versão atualizada?
No mesmo email que baixei pela primeira vez?

Agradeço a atenção.


Att
Dhenner Santos Peres

2015-01-21 16:10 GMT-02:00 Flavio Henrique de Souza Almeida <
notifications@github.com>:

> Como saber se o seu livro está atualizado? No CAP 08 tem a seção
> "Interceptadores do AngularJS".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/7#issuecomment-70889731>
> .
>



-- 
Att
Dhenner Santos Peres

**Comment by flaviohenriquealmeida** [comment]
Justo! É o mesmo e-mail. Para ter certeza que é a atualizada, verifique se no cap 08 há a seção "Interceptadores do Angular". 

Dhenner, agradeço já sua contribuição para a errata do livro, apesar de já ter recebido e corrigido a que você reportou. Se encontrar outra, me avise! Abraço!

**Comment by Dhenner** [comment]
Opa,
deu certo, já estou com o livro atualizado, um duvida como posso saber se
existe atualizações do livro disponível?


Agradeço a atenção.


Att
Dhenner Santos Peres

Em 21 de janeiro de 2015 17:37, Flavio Henrique de Souza Almeida <
notifications@github.com> escreveu:

> Justo! É o mesmo e-mail. Para ter certeza que é a atualizada, verifique se
> no cap 08 há a seção "Interceptadores do Angular".
>
> Dhenner, agradeço já sua contribuição para a errata do livro, apesar de já
> ter recebido e corrigido a que você reportou. Se encontrar outra, me avise!
> Abraço!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/7#issuecomment-70906282>
> .
>



-- 
Att
Dhenner Santos Peres

**Comment by flaviohenriquealmeida** [comment]
Você receberá um news letter ou será notificado pela twitter da casa do código. Essa versão foi atualizada rapidamente para dar tempo de sair a errada nos livros impressos, por isso você não foi avisado. 

Por exemplo, estamos planejando uma atualização sexta-feira (só se alguma errata aparecer nesse ínterim). Então, lá para segunda-feira pode ser que tenha uma nova versão. Depois disso, a ideia é ter apenas caso eu resolva adicionar um novo cap para tornar o livro melhor do que já é.

**Comment by Dhenner** [comment]
Bom dia,
no item 8.9 REST Endpoints: Permitindo apenas acesso autenticado,
adicionaremos as rotas em nossos controlador como diz o livro ou eu nossas
rotas?

app.route('/contatos')
.get(verificaAutenticacao, controller.listaTodos)
.post(verificaAutenticacao, controller.salvaContato);

app.route('/contatos/:id')
.get(verificaAutenticacao, controller.obtemContato)
.delete(verificaAutenticacao, controller.removeContato);


Att
Dhenner Santos Peres


Em 21 de janeiro de 2015 17:52, Flavio Henrique de Souza Almeida <
notifications@github.com> escreveu:

> Você receberá um news letter ou será notificado pela twitter da casa do
> código. Essa versão foi atualizada rapidamente para dar tempo de sair a
> errada nos livros impressos, por isso você não foi avisado.
>
> Por exemplo, estamos planejando uma atualização sexta-feira (só se alguma
> errata aparecer nesse ínterim). Então, lá para segunda-feira pode ser que
> tenha uma nova versão. Depois disso, a ideia é ter apenas caso eu resolva
> adicionar um novo cap para tornar o livro melhor do que já é.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/7#issuecomment-70908943>
> .
>



-- 
Att
Dhenner Santos Peres

**Comment by flaviohenriquealmeida** [comment]
É no arquivo de rota como você percebeu. Vou elaborar a errata.
Obrigado.

Em 22 de janeiro de 2015 10:06, Dhenner <notifications@github.com> escreveu:

> Bom dia,
> no item 8.9 REST Endpoints: Permitindo apenas acesso autenticado,
> adicionaremos as rotas em nossos controlador como diz o livro ou eu nossas
> rotas?
>
> app.route('/contatos')
> .get(verificaAutenticacao, controller.listaTodos)
> .post(verificaAutenticacao, controller.salvaContato);
>
> app.route('/contatos/:id')
> .get(verificaAutenticacao, controller.obtemContato)
> .delete(verificaAutenticacao, controller.removeContato);
>
>
> Att
> Dhenner Santos Peres
>
>
> Em 21 de janeiro de 2015 17:52, Flavio Henrique de Souza Almeida <
> notifications@github.com> escreveu:
>
> > Você receberá um news letter ou será notificado pela twitter da casa do
> > código. Essa versão foi atualizada rapidamente para dar tempo de sair a
> > errada nos livros impressos, por isso você não foi avisado.
> >
> > Por exemplo, estamos planejando uma atualização sexta-feira (só se
> alguma
> > errata aparecer nesse ínterim). Então, lá para segunda-feira pode ser
> que
> > tenha uma nova versão. Depois disso, a ideia é ter apenas caso eu
> resolva
> > adicionar um novo cap para tornar o livro melhor do que já é.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/7#issuecomment-70908943>
>
> > .
> >
>
>
>
> --
> Att
> Dhenner Santos Peres
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/7#issuecomment-71011115>
> .
>



-- 
"o único homem educado é o homem que aprendeu a aprender" - Carl R. Rogers

www.caelum.com.br

**Comment by flaviohenriquealmeida** [comment]
Amanhã à noite ou sábado pela noite você já poderá baixar o novo PDF com as
erratas. Sem que achar algo, pode utilizar este canal direto comigo.

Abraço!

Em 22 de janeiro de 2015 11:41, Flávio Henrique Almeida <
flaviohenriquealmeida@gmail.com> escreveu:

> É no arquivo de rota como você percebeu. Vou elaborar a errata.
> Obrigado.
>
> Em 22 de janeiro de 2015 10:06, Dhenner <notifications@github.com>
> escreveu:
>
> Bom dia,
>> no item 8.9 REST Endpoints: Permitindo apenas acesso autenticado,
>> adicionaremos as rotas em nossos controlador como diz o livro ou eu
>> nossas
>> rotas?
>>
>> app.route('/contatos')
>> .get(verificaAutenticacao, controller.listaTodos)
>> .post(verificaAutenticacao, controller.salvaContato);
>>
>> app.route('/contatos/:id')
>> .get(verificaAutenticacao, controller.obtemContato)
>> .delete(verificaAutenticacao, controller.removeContato);
>>
>>
>> Att
>> Dhenner Santos Peres
>>
>>
>> Em 21 de janeiro de 2015 17:52, Flavio Henrique de Souza Almeida <
>> notifications@github.com> escreveu:
>>
>> > Você receberá um news letter ou será notificado pela twitter da casa do
>> > código. Essa versão foi atualizada rapidamente para dar tempo de sair a
>> > errada nos livros impressos, por isso você não foi avisado.
>> >
>> > Por exemplo, estamos planejando uma atualização sexta-feira (só se
>> alguma
>> > errata aparecer nesse ínterim). Então, lá para segunda-feira pode ser
>> que
>> > tenha uma nova versão. Depois disso, a ideia é ter apenas caso eu
>> resolva
>> > adicionar um novo cap para tornar o livro melhor do que já é.
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/7#issuecomment-70908943>
>>
>> > .
>> >
>>
>>
>>
>> --
>> Att
>> Dhenner Santos Peres
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/7#issuecomment-71011115>
>> .
>>
>
>
>
> --
> "o único homem educado é o homem que aprendeu a aprender" - Carl R. Rogers
>
> www.caelum.com.br
>



-- 
"o único homem educado é o homem que aprendeu a aprender" - Carl R. Rogers

www.caelum.com.br

**Comment by flaviohenriquealmeida** [comment]
Olá. Conseguiu o PDF atualizado? :)

**Comment by Dhenner** [comment]
Ola,
acabei de baixar novamente e o erro continua na pagina 202 e 203 onde a
function verificaAuthenticacao() deve estar no arquivo contato.js na pasta
routes e o livro indica a pasta controllers.



Att
Dhenner Santos Peres

Em 23 de janeiro de 2015 12:04, Flavio Henrique de Souza Almeida <
notifications@github.com> escreveu:

> Olá. Conseguiu o PDF atualizado? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/7#issuecomment-71196961>
> .
>



-- 
Att
Dhenner Santos Peres

**Comment by flaviohenriquealmeida** [comment]
Olá, você teve acesso a versão com a primeira errata. Hoje, à meia-noite
atualizaremos novamente. Este problema reportado já foi corrigido,mas não
entrou na sua versão.

Se você não quiser esperar as erratas, pode se basear no código do meu
github.

Em 23 de janeiro de 2015 12:19, Dhenner <notifications@github.com> escreveu:

> Ola,
> acabei de baixar novamente e o erro continua na pagina 202 e 203 onde a
> function verificaAuthenticacao() deve estar no arquivo contato.js na pasta
> routes e o livro indica a pasta controllers.
>
>
>
> Att
> Dhenner Santos Peres
>
> Em 23 de janeiro de 2015 12:04, Flavio Henrique de Souza Almeida <
> notifications@github.com> escreveu:
>
> > Olá. Conseguiu o PDF atualizado? :)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/7#issuecomment-71196961>
>
> > .
> >
>
>
>
> --
> Att
> Dhenner Santos Peres
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaviohenriquealmeida/mean-livro-codigo/issues/7#issuecomment-71198929>
> .
>



-- 
"o único homem educado é o homem que aprendeu a aprender" - Carl R. Rogers

www.caelum.com.br
