### ISSUE TITLE
[OFF] Grupo no Facebook para a galera que comprou o livro

### ISSUE THREAD

**Issue by coreilabs** [flaviohenriquealmeida/mean-livro-codigo#8]
@flaviohenriquealmeida Criei este grupo no facebook para a galera que comprou seu livro trocar ideias, pode deixar ou devo desativar?

https://www.facebook.com/groups/1534163683531297/

**Comment by flaviohenriquealmeida** [comment]
Pode deixar. Obrigado!
Em 25/01/2015 21:19, "Marco Aurélio Silva" <notifications@github.com>
escreveu:
