### ISSUE TITLE
Erro Cap. 11.10

### ISSUE THREAD

**Issue by Dhenner** [flaviohenriquealmeida/mean-livro-codigo#9]
Meu protractor.js é o mesmo do repositório, estou com o selenium e o server rodando.

exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['../test/e2e/*.js'],
  onPrepare: function() {
    browser.driver.get('http://localhost:3000');
    browser.driver.findElement(by.id('entrar')).click();
    browser.driver.findElement(by.id('login_field'))
      .sendKeys('usuarioDoGitHub');
    browser.driver.findElement(by.id('password'))
      .sendKeys('senhaUsuarioGithub');
    browser.driver.findElement(by.name('commit')).click();  
  }
};

Estou com esse erro, ja chequei todas a possibilidades de causa.

Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
[launcher] Error: NoSuchElementError: no such element
  (Session info: chrome=40.0.2214.91)
  (Driver info: chromedriver=2.12.301324 (de8ab311bc9374d0ade71f7c167bad61848c7c48),platform=Linux 3.16.0-29-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 22 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'DELL-5437', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.0-29-generic', java.version: '1.7.0_75'
Session ID: b4add7911c0241ebc45f71cec70e8635
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.HHbpIu}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=40.0.2214.91, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
==== async task ====
WebDriver.findElement(By.id("entrar"))
    at exports.config.onPrepare (/home/dhenner/Development/source/mean-full-stack/contatooh/config/protractor.js:6:20)
==== async task ====
executing onPrepare
    at Function.promise (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:650:9)
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:759:13)
[launcher] Process exited with error code 100

**Comment by flaviohenriquealmeida** [comment]
Faltou Id entrar
Em 25/01/2015 22:41, "Dhenner" <notifications@github.com> escreveu:

**Comment by Dhenner** [comment]
Consegui mas eu já havia adicionado o id na page auth.html, só consegui apos alterar o protactor.js para:
browser.driver.get('http://localhost:3000/#/auth');

**Comment by flaviohenriquealmeida** [comment]
Não deveria alterar. veja se vc esqueceu de colar a cláusula otherwise na
rota do angular.  O que Vc vez não é boa prática.  Vc deve deixar o sistema
de rotas te levar.
Em 25/01/2015 23:06, "Dhenner" <notifications@github.com> escreveu:

**Comment by caiocutrim** [comment]
Oi de novo mestre rsrsrs eu não sei porque o selenium não reconhece a rota otherwise  do angular, pelo menos aqui...no ubuntu auheuaheuahe eu testei com aquela jumbotron que vc tirou do código aqui e funcionou, claro que indicando no brower.driver.get".../#/auth", acho que deve ser bug do selenium :/

**Comment by flaviohenriquealmeida** [comment]
Eu testei seu código, ele chama a rota sim. Tanto isso é verdade, que ele mostra a parcial na URL. Ou seja, seu otherwise está funcionando (caso contrário, ele não a exibiria). O problema bizarro é que você colocou div dentro de div com umas classes do bootstrap que deixou o selenium doido. Não sei o motivo. Para resolver, basta deixar aquela página sem estar aninhada. Só para frisar: vc não deve colocar no protractor o endereço apontando para #/auth. É uma má pratica, porque quem deve fazer esse direcionamento para você é o sistema de rotas do angular através do interceptador.

**Comment by flaviohenriquealmeida** [comment]
Caio, tá de boa agora? Funcionando? Não custa lembrar: se o id entrar ficar na tag a, o selenium (Protractor) não conseguirá achar o elemento. Por isso ele precisa estar dentro d h1 que fica dentro da a.

**Comment by caiocutrim** [comment]
cara é um bug na distro kkkk q bizarro, testei no mac, e tudo certo...

**Comment by caiocutrim** [comment]
eu não dei o feedback antes pq tava ocupadão

**Comment by caiocutrim** [comment]
vou fazer os mesmos testes com casper.js :)

**Comment by Dhenner** [comment]
Utilizou Ubuntu 14.10 também tive que utilizar a URL completa.
Em 31/01/2015 13:23, "Caio Cutrim" <notifications@github.com> escreveu:

**Comment by flaviohenriquealmeida** [comment]
Dhenner, é esse repo que posso considerar para entender o que houve no seu projeto? https://github.com/Dhenner/contatooh

Curiosidade: qual é o navegador de vocês, versão? Quando o interceptador do angularjs detecta que você não está logado, ele chama a rota /auth. É essa rota que joga para a tela de login. Como o protractor está chando 'http://localhost:8080/ ele tentará acessar a parcial contatos.html, mas será direcionado. Eu testei aqui, funcionou. Pedi feedback para outros leitores e funcionou. Mas eu fiquei interessado no caso de vocês, porque pode acontecer com outro leitor, por isso vou investigar com carinho :)

Abraço!

**Comment by caiocutrim** [comment]
eu to usando chrome para os, testes e tá na última versão 40.02

**Comment by Dhenner** [comment]
Chrome: Versão 40.0.2214.94 (64-bit)
Sim, este é meu código atual.
Obrigado.

**Comment by flaviohenriquealmeida** [comment]
Dhenner, eu verifiquei seu repositório. Eu subo seu servidor, rodo o protractor (removi o #auth) do caminho do protractor. O navegador que abre faz o redirect para o o auth.html conforme esperado.
Porém, vi que você adicionou no seu protractor.js uma configuração que eu não indiquei no livro:

 seleniumAddress: 'http://localhost:4444/wd/hub'

Você precisa remover essa configuração, não é necessária. Inclusive, caso esteja presente, você terá problemas na hora de rodar seu projeto com o sauce labs. 

Qualquer dúvida, estou aqui. 

Caio, assim que puder, vejo o seu.

**Comment by caiocutrim** [comment]
Beleza meu querido

**Comment by caiocutrim** [comment]
ta dando esse erro no deploy
Warning: Permanently added 'contactooh-maranhao.rhcloud.com' (RSA) to the list of known hosts.Counting objects: 3571, done.Delta compression using up to 32 threads.Compressing objects: 100% (2636/2636), done.Writing objects: 100% (3571/3571), 5.08 MiB | 0 bytes/s, done.Total 3571 (delta 562), reused 3551 (delta 553)error: Could not read 18e918d91ed099b2921208befdc81bea63dde42cfatal: revision walk setup failederror: Could not read 18e918d91ed099b2921208befdc81bea63dde42cfatal: revision walk setup failedremote: Stopping NodeJS cartridgeremote: MongoDB already stoppedremote: Repairing links for 1 deploymentsTo ssh://54d935204382ec143a00007e@contactooh-maranhao.rhcloud.com/~/git/contactooh.git/ ! [remote rejected] master -> master (missing necessary objects)error: failed to push some refs to 'ssh://54d935204382ec143a00007e@contactooh-maranhao.rhcloud.com/~/git/contactooh.git/'Already up-to-date!# On branch master# Your branch is ahead of 'origin/master' by 1 commit.#   (use "git push" to publish your local commits)## Untracked files:#   (use "git add <file>..." to include in what will be committed)##	.dpl/#nothing added to commit but untracked files present (use "git add" to track)Dropped refs/stash@{0} (ed6c12865cf63f71440a2c6e185ef9894bae4e6c)Done. Your build exited with 0.

**Comment by caiocutrim** [comment]
é esse erro
https://travis-ci.org/caiocutrim/contactooh/builds/50142506

**Comment by caiocutrim** [comment]
consegui resolver por aqui com um dos programadores do openshift-cli
https://github.com/travis-ci/travis-ci/issues/2956#issuecomment-73635134

**Comment by flaviohenriquealmeida** [comment]
Hum, se você não segui à risca os passos do livro poderá ter sérios problemas. Por exemplo, há no seu travis.yml o parâmetro skip_cleanup: true, não deveria ter. Há também uma discrepância entre os três repositórios aí, a causa, não faço ideia :)

Primeiro, verifique seu travis.yml se está condizente com o que está no livro. Depois, veja se o seu repo do Openshift está íntegro. Por hora, são essas minhas recomendações.

**Comment by flaviohenriquealmeida** [comment]
Verifique dobrado se você respondeu como o livro indica às perguntas do comando travis setup openshift.
